### ISSUE TITLE
Prefix transition

### ISSUE THREAD

**Issue by mxstbr** [thysultan/stylis.js#1]
```CSS
transition: xy;

/* should become */

transition: xy;
-webkit-transition: xy;
```

According to CanIUse, by not prefixing we lose about 10% usage support due to UC Browser for Android.

![screen shot 2016-12-04 at 11 53 07](https://cloud.githubusercontent.com/assets/7525670/20865657/4a0ae10a-ba18-11e6-889e-ec847d920395.png)

http://caniuse.com/#feat=css-transitions

**Comment by thysultan** [comment]
transitions are prefixed, i think this issue is related to the property not being in a & {} block, i'll add a patch for this.

```
stylis('.something', `

  > h1 {
    transition: xy;
  }

`)
```

".something > h1 {-webkit-transition: xy;-moz-transition: xy;-ms-transition: xy;transition: xy;}"
