### ISSUE TITLE
Tests for rule-sheet plugin

### ISSUE THREAD

**Issue by thysultan** [thysultan/stylis.js#100]

**Comment by kopax** [comment]
Hi @thysultan, is this a test module for stylis stylesheet?

We found hard to test our stylis string to be valid generated CSS after.

**Comment by kopax** [comment]
For instance see these two projects:

- github.com/bootstrap-styled/css-mixins
- github.com/bootstrap-styled/css-utils

We have css utilities and mixins in stylis format.

So far we test checksum with json so it force to pay attention.

We also search if the generated string contain.

We'd like to test the styles that the one with configured is correct. It could have done better but we were waiting for styled components test utils to emerge but that is still unexisting.

/cc @santaclauze

**Comment by thysultan** [comment]
Can you elaborate on what you mean by "stylis format"?

Is there any reason you aren't using the CSSOM or `getComputedStyle `?

**Comment by kopax** [comment]
Considerong `input` is whatever and `output` is the valid css, a `valid stylis format` would be **anything**  stylis would accept as input string that would return valid css string after stylis processing.

Issues we had issues to test for examples where  : 

- variables passed to styled where `undefined` within styled-component `theme` and `undefined` within the generated mixins, wihile `undefined` or `null` is not a valid css value.
- missing block opening or closing brace `{` or `}` 
- missing `;` after css rules

I am not aware of those two, how can they help?

**Comment by Andarist** [comment]
This is no longer relevant for v4. It already has a simple test for its `rulesheet` plugin and doesn't require much more as actual insertion is offloaded to the passed-in callback, so it's completely consumer's responsibility.
