### ISSUE TITLE
disabled cascade and specificity

### ISSUE THREAD

**Issue by giuseppeg** [thysultan/stylis.js#101]
We realized that disabling cascade and scoping every selector breaks specificity eg.

Say we have:

```css
div > div > span // specificity [0,0,0,3]
.clickTest // specificity [0,0,1,0]
```

When each selector is scoped the specificity becomes:

```
[0,0,3,3]
[0,0,2,0]
```

Now the first selector is more specific than the second - it wasn't the case with the original selectors.

To solve this issue I think that we could just scope the last selector:

```css
div > div > span.jsx-123 // specificity [0,0,1,3]
.clickTest.jsx-123 // specificity [0,0,2,0] <- this still wins
```
@thysultan would it be hard to make this change and maybe release a major version?

**Comment by thysultan** [comment]
I think the current heuristics was the hardest part, that said would this change still isolate(in the broader sense) the cascade in the same fashion that the current heuristics intended it to?

**Comment by giuseppeg** [comment]
we'd need to do some thinking and try to isolate the edge cases, eg. mixed scoped and global styles. But I think that most of the time this should work just fine.

**Comment by thysultan** [comment]
>eg. mixed scoped and global styles. 

Do you have examples of these edge cases?

**Comment by giuseppeg** [comment]
Yep there is an edge case with `:global` see the first example:
https://jsfiddle.net/aeznqkyw/

**Comment by giuseppeg** [comment]
so when the last selector is `:global` we should scope the last non-global selector

**Comment by giuseppeg** [comment]
I just checked and Vue uses the same technique (scoping the last selector). As I said above we also need to support the `:global` special case. How hard would it be to implement this way of scoping?

**Comment by giuseppeg** [comment]
Ok here's another edge case https://jsfiddle.net/aeznqkyw/10/ see the _nested edge case_ basically if we only scope the innermost selector other components can cause the selector to match anyway. 

The solution I guess is to always scope the innermost and outermost selectors. To not break specificity then we need to add the scoped class twice when the selector is single eg. `div.jsx-123.jsx-123` https://jsfiddle.net/aeznqkyw/14/

**Comment by thysultan** [comment]
Have i missed out anything in the following list:

```scss
// leading :global 
:global(div) div div {}
div div.ns div.ns {}

// trailing :global 
div div :global(div) {}
div.ns div.ns div {}

// inner :global
div :global(div) div span {}
div.ns div div span.ns {}

// single + leading :global
:global(span) div {}
span div.ns.ns {}

// single + trailing :global
div :global(span) {}
div.ns.ns span {}

// single
.bar {}
.bar.ns.ns {}

// multiple
.bar .foo .faz {}
.bar.ns foo .faz.ns {}

// two(similar to multiple)
.bar .foo {}
.bar.ns foo.ns {}
```

**Comment by giuseppeg** [comment]
@thysultan yes those should be all 👌

**Comment by giuseppeg** [comment]
@thysultan let me know if I can help out with this, I would like to include the fix into styled-jsx v3

**Comment by thysultan** [comment]
@giuseppeg Sure, the crux of this would apply to the [isolate](https://github.com/thysultan/stylis.js/blob/master/stylis.js#L1331-L1417) function, specifically the switch from [line#1364](https://github.com/thysultan/stylis.js/blob/master/stylis.js#L1364-L1411). I hope to get to work on this once i'm done with [DIO 9.0.0](https://github.com/thysultan/dio.js/pull/52) release this/next week. The `for` block from [line#1337](https://github.com/thysultan/stylis.js/blob/master/stylis.js#L1337) iterates through the different parts(i.e `div` in `div h1`) of a single selector(i.e `div h1` in `div h1, span h2`).

**Comment by giuseppeg** [comment]
@thysultan unfortunately I haven't had enough free time to work on this or even try to understand how Stylis is scoping selectors :( Would it be a lot of work for you to fix it?

**Comment by thysultan** [comment]
Sure, no problem.

**Comment by giuseppeg** [comment]
@thysultan got any rough idea about the ETA for this fix? (I don't want to put pressure on you... take your time, it is just for my information)

**Comment by thysultan** [comment]
@giuseppeg Do you know of any situation where this will break current use, that is can it go into a patch version?

**Comment by giuseppeg** [comment]
I think it might break if one relies on the wrong specificity or hacked something together to make a selector work (eg bump the specificity until it worked :). I am thinking to include this change (the last thing missing to) 
in styled-jsx v3 but leave v2 as-is

**Comment by giuseppeg** [comment]
@thysultan do you have any update on this?

**Comment by thysultan** [comment]
Thanks for the ping. I haven't gotten to work on this yet.

**Comment by thysultan** [comment]
Not sure, i've started a [rewrite](https://github.com/thysultan/stylis.js/tree/master/rewrite) for v4 that i plan to include this into if things go well.

**Comment by giuseppeg** [comment]
oh wow that looks amazing! No pressure anyway, would you still release stylis as v4 if we fix this before your rewrite?

**Comment by Andarist** [comment]
@thysultan from what I understand `namespace` in v4 **doesn't** implement the heuristics discussed here, should we pursue implementing them instead what is currently on v4 branch (and what probably matches v3 heuristics)?

**Comment by Andarist** [comment]
The `namespace` plugin on v4 branch is now implementing heuristics discussed here.
