### ISSUE TITLE
context code for "selector"?

### ISSUE THREAD

**Issue by FezVrasta** [thysultan/stylis.js#102]
I'd like to alter a selector writing my own plugin, but I can't seem to find a `context` code that will return me as `content` the selector.

What's the right way to do it?

I'd like to write a plugin that converts `.foo:bar {}` to `.foo:baz {}`

**Comment by thysultan** [comment]
The `selectors` array passed to plugins is mutable so you could mutate it in the `2  /* selector block context */` context, that said there might be value in a dedicated context for a selector context before name-spacing is applied.

**Comment by FezVrasta** [comment]
Oh thanks! I didn't realize it was mutable, thanks.

**Comment by thysultan** [comment]
Np, ping back with how that goes and if a dedicated context would indeed better serve this design pattern.

**Comment by FezVrasta** [comment]
So this is my plugin so far:

```
const plugin = (
  context: number,
  content: string,
  selectors: Array<string>,
  parents: Array<string>,
  line: number,
  column: number,
  length: number
) => {
  if (context === 2) {
    selectors.forEach((selector, index) => {
      selectors[index] = selector.replace(':bar', ':baz');
    });
  }

  return content;
};
```

But from what I see it's not actually manipulating the selectors, they remain the same. Am I missing something I guess?

**Comment by thysultan** [comment]
That works for me, what did you mean by `they remain the same`?

```js
const plugin = (context, content, selectors, parents, line, column, length) => {
  if (context === 2) {
    selectors.forEach((selector, index) => {
      selectors[index] = selector.replace(':bar', ':baz');
    });
  }

  return content;
};

stylis.use(plugin)

var output = stylis('#id', `
.foo:bar {
  color:red;
}
`)

console.log(output)
```

**Comment by FezVrasta** [comment]
Right sorry, I must have messed something up. It works thanks again
