### ISSUE TITLE
Multi-level descendant selectors break with when using global and split across lines 

### ISSUE THREAD

**Issue by masad-frost** [thysultan/stylis.js#104]
Here's a simple demo: https://repl.it/@masfrost/StylisMultilineDecendant

If you do 1 level it works fine, anything after that produces weird results.

**Comment by thysultan** [comment]
Fixed in 3.5.1

**Comment by masad-frost** [comment]
Thank you!

**Comment by masad-frost** [comment]
Looks like this was never resolved? Or not fully at least
