### ISSUE TITLE
TS any type

### ISSUE THREAD

**Issue by Ailrun** [thysultan/stylis.js#106]
Even though return type of `stylis` function includes `any` type, it looks like calling `stylis` cannot return `any` type, i.e., `proxy` function cannot return `any` type unless any plugin returns `any`, and `Plugin` type forbid such return, so there's no way to return `any` type.

Is there any reason for that `any` type in return type? Is my analysis wrong?

**Comment by thysultan** [comment]
Yes this looks like an issue with the typings definitions, plugins are able to return any arbitrary type specifically in the post-process phase. Can you open a pull request with the amended changes?

**Comment by Ailrun** [comment]
@thysultan So you mean the wrong one is the typing of `Plugin`, not the typing of `stylis` function or, ... right?
I will open a PR for this.

**Comment by thysultan** [comment]
Yes, the `Plugin` return type in stylis.d.ts.
