### ISSUE TITLE
"v-text-anchor" property is broken

### ISSUE THREAD

**Issue by ashtonsix** [thysultan/stylis.js#108]
- `stylis` version: 3.5.0

Minimal Example:

```javascript
style = stylis(``, `
  div {
    v-text-anchor: middle;
    color: rebeccapurple;
  }
`);

console.log(style) // "v-text-anchor:middle;div{color:rebeccapurple;}"
```

Without the `color` property, the generated css looks like `"v-text-anchor:middle;"`

I'd expect the generated css to look like this instead:

`"div{color:rebeccapurple;v-text-anchor:middle;}"`

All properties that match `/^v-/` seem to break.

[Downstream issue in Emotion](https://github.com/emotion-js/emotion/issues/716)

[![Edit kwy6x3pvvv](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kwy6x3pvvv)

<details>
<summary>Real-World Example (spoiler):</summary>
There's a few intermediate build steps, but this generates VML for displaying rounded buttons in older versions of Outlook (using Emotion).
<pre><code>return (
  &lt;center>
    &lt;if condition="mso">
      &lt;v$roundrect
        xmlns$v="urn:schemas-microsoft-com:vml"
        xmlns$w="urn:schemas-microsoft-com:office:word"
        href={link}
        className="emailButton"
        css={`
          width: ${width};
          height: ${height};
          v-text-anchor: middle;
        `}
        fillcolor={background}
        arcsize={arcsize}
        stroke="f"
      >
        &lt;w$anchorlock />
        &lt;center
          css={`
            color: ${color};
            font-size: ${fontSize};
          `}
        >
          {children}
        &lt;/center>
      &lt;/v$roundrect>
    &lt;/if>
    &lt;else condition="mso">
      &lt;a
        href={link}
        className="emailButton"
        css={`
          display: block;
          width: ${width}px;
          line-height: ${height}px;
          -webkit-text-size-adjust: none;
          background-color: ${background};
          border-radius: ${borderRadius}px;
          font-size: ${fontSize}px;
          color: ${color};
        `}
      >
        {children}
      &lt;/a>
    &lt;/else>
  &lt;/center>
)</code></pre>
</details>

**Comment by thysultan** [comment]
Fixed in 3.5.1
