### ISSUE TITLE
Block comment with closebraces breaking generation or causing infinite loop

### ISSUE THREAD

**Issue by AllainPL** [thysultan/stylis.js#110]
Hi i found a problem with stylis.js while using styled-components with css rules having block comments with `}` - closing braces - inside rules.
The minimal breaking examples I found are `/* } */` and `/*}*/`.

The first one `/* } */` just breaks the generated output:
```js
'CLOSEBRACES in block comment': {
	sample:`.a{color:red;/* } */}`,
	expected:`.user .a{color:red;}`
},
```
Test result:
```
31 'failed: ' 'infinite loop' '\n\n' '.user{*/};}.user .a{color:red;}'
20 'expected: ' '\n\n' '.user .a{color:red;}' '\n\n---------------\n\n'
false
```

However this `/*}*/` or `/* )} */`:
```
'infinite loop': {
	sample:`.a{color:red;/*}*/}`,
	expected:`.user .a{color:red;}`
},
```
Causes an infinite loop in stylis.js line 214
```
// ...build body
while (caret < eof) {
```
with `caret` and `eof` being both incremented.

**Comment by AllainPL** [comment]
Found some more breaking cases.
**First:**
```js
'inline comment in block comment': {
	sample:`.a{color:red; /*// */}`,
	expected:`.user .a{color:red;}`
},
```
Test result:
```
25 'failed: ' 'comment leak' '\n\n' '.user .a{color:red;/ */;}'
20 'expected: ' '\n\n' '.user .a{color:red;}' '\n\n---------------\n\n'
```

**Second:**
```
'OPENBRACES in block comment': {
	sample:`.a{
			/* { */
		}
		.b{
			color: red;
		}`,
	expected:`.user .b{color:red;}`
},
```
Test result:
```
23 'failed: ' 'comment leak' '\n\n' '.user .a .b{color:red;}'
20 'expected: ' '\n\n' '.user .b{color:red;}' '\n\n---------------\n\n'
```

**Third:**
```
'OPENBRACES in inline comment': {
	sample:`.a{ // }
		color:red;}`,
	expected:`.user .a{color:red;}`
},
```
Test result:
```
17 'failed: ' 'OPENBRACES in inline comment' '\n\n' '.user{color:red;}'
20 'expected: ' '\n\n' '.user .a{color:red;}' '\n\n---------------\n\n'
```

**Fourth:**
```
'CLOSEBRACES in inline comment': {
	sample:`.a{
			// {
		}
		.b{
			color: red;
		}`,
	expected:`.user .b{color:red;}`
},
```
Test result:
```
23 'failed: ' 'CLOSEBRACES in inline comment' '\n\n' '.user .a .b{color:red;}'
20 'expected: ' '\n\n' '.user .b{color:red;}' '\n\n---------------\n\n'
```

The cause of issues with braces in comments lays in braces matching algorithm. After encountering `{` algorithm seeks for matching `}` in a very simple loop (lines 318-337) that ignores everything else. That results in commented braces being matched too and in effect, `compile` function being called with wrong context.

**Comment by aczekajski** [comment]
In my opinion, the whole algorithm responsible for extracting contexts is totally wrong in its roots. This is not how parsers should be written. First thing is, algorithm like this shouldn't be written using recurrence. But let's leave the recurrence aside for a while. The main problem lays in the idea of matching braces. Let's consider example like that:
```.a{.b{.c{.d{.e{.f{.g{.h{.i{ }}}}}}}}}```
After reading `.a{` algorithm reads the remaining string a char after char, changing counter with every `{` or `}` and calls `compile` with
```.b{.c{.d{.e{.f{.g{.h{.i{ }}}}}}}}```
as body. From this point, algorithm continues, reading the same chars over and over again.

In my opinion, the recurrent calls should look like this:
1. `.a{ .b{ /*...*/ } }` - first call
1. ` .b{ /*...*/ } }` - second call
1. ` /*...*/ } }` - third call. Now the usual algorithm parses this string and when it encounters `}`, it returns current results and the `} }` as a remaining string
1. Back in second call, algorithm already parsed `.b{`, has a result of nested compiling, and knows that there's a remaining `} }` after that. Parsing continues, first `}` is a matching bracket, second `}` does not match to anything in current context so it causes this call to return results with `}` as a remaining string
1. First call continues analogically. Remaining `}` is a matching bracket and then `eof` is encountered.

**Comment by thysultan** [comment]
@aczekajski Steps 3 and 2 cannot be disjointed as any valid css can appear between `a` and `b`. i.e `.a{ color:red; .b{ /* ... */ } }`. What idea did you have in mind that doesn't use recurrence tracking.

**Comment by aczekajski** [comment]
It's not a problem. If step 1 is
```less
.a{
  color: red;
  .b{ /*...*/ }
  width: 100px;
}
```
then step 2 becomes
```less
  color: red;
  .b{ /*...*/ }
  width: 100px;
}
```
so the algorithm parses the color style properly and then reads `.b{` which causes third `compile` call, this time with
```less
 /*...*/ }
  width: 100px;
}
```
Third step returns result of parsing `/*...*/` and the remaining string:
```less
}
  width: 100px;
}
```
Now (back in second call) it parses first `}` as matching with previous `.b{`, then normally parses `width: 100px;` and after second `}` it continues just as I described.

I am not entirely sure but it looks like it's possible to write the algorithm without recurrence but with the stack. Every time algorithm needs to run on an isolated context, current state is pushed to stack, context that needs to be parsed is pushed too and the main algorithm loop restarts from popping from stack. Main loops continues until stack is empty. This is the way in which usually recurrence is removed from the algorithms like this. However, I understand that it might require complete rewrite of stylis main algorithm flow.

**Comment by AllainPL** [comment]
This is serious since it affects styled-components: https://github.com/styled-components/styled-components/issues/1842

**Comment by thysultan** [comment]
Patched in 3.5.2

**Comment by aczekajski** [comment]
@thysultan Thank you for fast reaction!

Unfortunately there are still scenarios in which current algorithm fails.

**First:**
Input:
```less
.a{color:red;/*//
color:blue;*/}
```
Expected:
```css
.user .a{color:red;}
```
Actual:
```css
.user .a{color:red;color:blue;*/;}
```

**Second:**
Input:
```less
.a {
  background: url("img}.png");
}
```
Yes, this is unfortunately a valid css.
Expected:
```css
.user .a{background:url("img}.png");}
```
Actual:
```css
.user{.png");;}.user .a{background:url("img;}
```

**Comment by thysultan** [comment]
Thanks for the additional edge cases, 3.5.3 should fix these and more. i.e parenthesis 
 and bracket variants `a{ background:url(img}.png); [img}]{color:red;} }`
