### ISSUE TITLE
No semicolons fails with css functions

### ISSUE THREAD

**Issue by martinmacko47** [thysultan/stylis.js#115]
If I understand no semicolons support as described in #12 correctly the following:
```
background-image: radial-gradient(black 0%, green 100%)
color: red
```

should transpile to:
```
background-image: radial-gradient(black 0%, green 100%);
color: red;
```

However it transpiles to:
```
background-image: radial-gradient(black 0%, green 100%) color: red;
```

**Comment by probablyup** [comment]
This happens for `url()` syntax too: https://github.com/styled-components/styled-components/issues/2186

**Comment by Andarist** [comment]
Support for no semicolons has been removed in the upcoming v4. So it doesn't seem worth tracking this issue anymore, hope you understand.
