### ISSUE TITLE
wrong parsing of custom syntax inside calc

### ISSUE THREAD

**Issue by eranshabi** [thysultan/stylis.js#116]
when parsing using the following code:
```
var Stylis = require("stylis")

const stylis = new Stylis({semicolon: false, compress: false, preserve: true});

console.log(stylis('', `.a .b .c {
  width: calc(100% / "func()");
}

.d {
  background: yellow;
}`))

```

the result is:
> ".a .b .c{width:calc(100% / \"func()\");}.a .b .c .d{background:yellow;}"

instead of:
> ".a .b .c{width:calc(100% / \"func()\");} .d{background:yellow;}"

The first selector was duplicated into the next selector.

**Comment by Andarist** [comment]
This got fixed in the upcoming v4:
https://github.com/thysultan/stylis.js/blob/5cb4a8a7541ba224d77825900790bb38768362d6/test/index.js#L808-L823
