### ISSUE TITLE
RTL Plugin

### ISSUE THREAD

**Issue by jopdeklein** [thysultan/stylis.js#117]
Hi!

I wrote a very simple RTL plugin for Stylis that uses CSSJanus to support LTR -> RTL conversion. If you'd like feel free to link to it or incorporate it into Stylis itself to bring RTL support to the Stylis community.

https://github.com/FindHotel/stylis-rtl

**Comment by thysultan** [comment]
v4 overhauls the plugin system so this probably wouldn't work there, but i like the suggestion of having some section to list stylis plugins/middlewares, maybe a wiki.
