### ISSUE TITLE
 weirdness with media queries and multiple new lines (and spaces)

### ISSUE THREAD

**Issue by jlmitch5** [thysultan/stylis.js#120]
Directed here from this styled-jsx issue: https://github.com/zeit/styled-jsx/issues/490

#### Do you want to request a *feature* or report a *bug*?

*bug*

when > 1 new line (with spaces at the beginning of at least two of the new lines) separate two media queries, the second media query becomes malformed.

```
      @media only screen and (max-width: 800px) {
        * {
          white-space: normal !important;
        }
      }
      
      
      @media only screen and (max-width: 730px) {
        .MusicProjects {
          grid-template-columns: 1fr;
        }
      }
```

#### What is the current behavior?

renders to:

```
@media only screen and (max-width: 800px) {
  * {
    white-space:normal !important;
  }
}

@media only screen and (max-width: 730px) .MusicProjects {
  grid-template-columns:1fr;
}
```

#### What is the expected behavior?

would expect it to render to:

```
@media only screen and (max-width: 800px) {
  * {
    white-space:normal !important;
  }
}

@media only screen and (max-width: 730px) {
  .MusicProjects {
    grid-template-columns:1fr;
  }
}
```

#### Environment (include versions)

* OS: macOS 10.13.6
* Browser: Chrome 68.0.3440.106
* stylis 3.5.3 (via styled-jsx 3.0.3-canary.0, next 7.0.0-canary.18)

**Comment by thysultan** [comment]
Are you able to reproduce this outside of styled-jsx? I couldn't reproduce this on https://stylis.js.org/

**Comment by jlmitch5** [comment]
hmm, yes I can't reproduce in that form either.  The rules are in global tag (`<style jsx global></style>`), I wonder if it might have something to do with that?  Unsure, I can investigate.

**Comment by jlmitch5** [comment]
removing the global attr and wrapping styles in just `<style jsx></style>` shows the same sort of class-in-media-query issue as above (with an additional issue where the scope class is appended to max-width).  I get

```
            @media only screen and (max-width.jsx-4203754750: 730px) .MusicProjects {
                grid-template-columns:1fr;
            }
```

I'm gonna circle back on the issue filed in styled-jsx.  I'll close this for now, thanks for the help!

**Comment by giuseppeg** [comment]
@thysultan this is an issue in Stylis when `cascade` is set to `false`. 
Can you add a checkbox to toggle `cascade` in the repl?

I could reproduce by opening the devtools and typing: `stylis.set({ cascade: false })` with this css:

```css
@media only screen and (max-width: 800px) {
        * {
          white-space: normal !important;
        }
      }
      
      
      @media only screen and (max-width: 730px) {
        .MusicProjects {
          grid-template-columns: 1fr;
        }
      }
```
