### ISSUE TITLE
Ability to specify a local static component scope for self-composition selectors

### ISSUE THREAD

**Issue by probablyup** [thysultan/stylis.js#124]
I'd like the ability to specify what `&` resolves to when it's standalone or referring to the root local scope. For example, in styled-components:

```jsx
const Component = styled.div`
  color: ${p => p.color};

  &[data-foo="bar"] {
    color: blue;
  }

  & + & {
     margin-left: 4px;
   }
`;
```

I believe the `&[data-foo="bar"]` will resolve to something like `.a[data-foo="bar"]` which is fine, but I'd want `& + &` to resolve to `.sc-foo + .sc-foo`, ".sc-foo" being the component static local scope (today it's like `.a + .a`).

**Comment by thysultan** [comment]
I don't understand. If you pass `.sc-foo` as the namespace wouldn't that work as well? i.e what is `a` in this context.

**Comment by probablyup** [comment]
When a component refers to itself, I want it to use the static className instead of the dynamic one. For example:

```jsx
const Component = styled.div`
  color: ${p => p.color};

  &[data-foo="bar"] {
    color: blue;
  }

  & + & {
     margin-left: 4px;
   }
`;
```

The & + & would be `.a + .a` which means if you compose two instances of `<Component>` next to each other with different props that selector won't function anymore (example: https://codesandbox.io/s/xpk25v94rz).

But if we make `&` refer to the static name, then it will work since every instance of `<Component>` has the ".sc-foo" class regardless of what styles are used.

**Comment by thysultan** [comment]
Is there any reason why you aren't doing this already? i.e passing the static class name to stylis instead of the dynamic one, 

>a would be the className that stylis dynamically generates

stylis doesn't generate it's own class name. What do you mean by this?

**Comment by probablyup** [comment]
Oh hmm. Ok I’ll dig more on my end.

**Comment by probablyup** [comment]
You're totally right, thanks for letting me ping pong off you!
