### ISSUE TITLE
Surprising behaviour of :global(x, y, z)

### ISSUE THREAD

**Issue by callumlocke** [thysultan/stylis.js#127]
Please see issue description here: https://github.com/zeit/styled-jsx/issues/506

In summary, the selector `.base :global(h1, h2, h3)` is compiled to something like `.base h1, h2, h3`, which seems wrong, or at least surprising.

styled-jsx maintainer @giuseppeg suggests it might be a bug in stylis?

**Comment by thysultan** [comment]
Yes it does look surprising, maybe it should work like `:matches()` in that regard. Not sure what heuristic css-modules uses in comparison.

**Comment by Andarist** [comment]
`:global` support is being dropped from stylis in the upcoming v4, so there is no much sense in discussing this particular issue further

**Comment by giuseppeg** [comment]
Interesting, why is that? I believe that many libs rely on that

**Comment by Andarist** [comment]
I think @thysultan wants to avoid parsing overhead associated with that and you can always write your rules without this. Most likely it will be possible to bring back support for this with a plugin. @thysultan could you correct me if im wrong?

**Comment by thysultan** [comment]
Yes, this will be a plugin.
