### ISSUE TITLE
Nested CSS Function inside escaped string breaks stylis conversion

### ISSUE THREAD

**Issue by olehreznichenko** [thysultan/stylis.js#128]
Forwarded from styled-components issue
https://github.com/styled-components/styled-components/issues/2121#issuecomment-433160342

**Comment by thysultan** [comment]
Do you have a repro of this outside of s-c?

**Comment by olegreznichenko** [comment]
I can create.
Codesandbox or repo? and example with using stylis or only native css?

**Comment by thysultan** [comment]
Codesandbox would be great.

**Comment by olegreznichenko** [comment]
@thysultan https://codesandbox.io/s/9yzn7krl9r

**Comment by Dremora** [comment]
Related: #116, #123.

**Comment by Andarist** [comment]
This got fixed in the upcoming v4:
https://github.com/thysultan/stylis.js/blob/5cb4a8a7541ba224d77825900790bb38768362d6/test/index.js#L791-L806
