### ISSUE TITLE
cursor: image-set() not being prefixed

### ISSUE THREAD

**Issue by 1000hz** [thysultan/stylis.js#130]
Similar to #105, `image-set` is not being given the `-webkit-` prefix when used inside a `cursor:` declaration.

The following modified spec fails:
```js
	'vendor prefixing VIII': {
		sample: `
			background:image-set(url(foo.jpg) 2x);
			background-image:image-set(url(foo.jpg) 2x);
			cursor:image-set(url(foo.jpg) 2x), grab;
		`,
		expected: ``+
		`.user{`+
			`background:-webkit-image-set(url(foo.jpg) 2x);`+
			`background:image-set(url(foo.jpg) 2x);`+
			`background-image:-webkit-image-set(url(foo.jpg) 2x);`+
			`background-image:image-set(url(foo.jpg) 2x);`+
			`cursor:-webkit-image-set(url(foo.jpg) 2x), -webkit-grab;`+
			`cursor:image-set(url(foo.jpg) 2x), -moz-grab;`+
			`cursor:image-set(url(foo.jpg) 2x), grab;`+
		`}`
	},
```

**Comment by thysultan** [comment]
Yes, we can add this. Do you want to try contributing this patch? It should be similar to the one listed for background-image.

**Comment by 1000hz** [comment]
I had tried when I filed the issue and got it working for everything but the `cursor:image-set(url(foo.jpg) 2x), grab;` case where it needs to prefix both `image-set` and `grab` in the same rule.   I've since deleted my copy of the repo. 😞

I'll try to redo what I had and send in a PR and we can work on fixing that failing case.

**Comment by thysultan** [comment]
Sounds good 👍

**Comment by Andarist** [comment]
@thysultan do we want to support prefixing this in v4?

**Comment by thysultan** [comment]
Yes, it's on the backburner of PR's to review for V4

**Comment by Andarist** [comment]
This got fixed on the v4 branch.
