### ISSUE TITLE
Missing vendor-prefixes for line-clamp, box-orient and diplay:box

### ISSUE THREAD

**Issue by karolfalkiewicz** [thysultan/stylis.js#131]
I wrote a function used by my styled-components that limit lines of visible text. It use few experimental things that can be vendor prefixed. None of the posible vendor prefixes is added after build, runtime. Is there any way to fix this?

Code that should have vendor prefixes (box-orient, line-clamp, display: box):
![zrzut ekranu 2018-11-22 o 08 50 04](https://user-images.githubusercontent.com/36987335/48903470-e79c1280-ee5b-11e8-9d52-6693d2c1a3bb.png)

**Comment by thysultan** [comment]
Can you more detail with regards to these experimental things. Does autoprefixer vendor prefix them. Is there any downside to doing the same(given their experimental nature)?

**Comment by karolfalkiewicz** [comment]
If I remember correctly the autoprefixer does vendor prefix them. Right now only webkit supports those tags, but this may change in the future.

**Comment by Andarist** [comment]
Looking at https://autoprefixer.github.io/ it doesn't seem that those are actually being prefixed by AutoPrefixer. If I'm wrong please correct me and I will reopen this.
