### ISSUE TITLE
'background-clip: text' not vendor prefixed

### ISSUE THREAD

**Issue by dschu-lab** [thysultan/stylis.js#132]
Hey there,
while trying to add an image-clipping effect on some text I've discovered that `background-clip: text` doesn't get vendor prefixed. 

Is this expected behaviour?

I've created a minimal reproducible example: https://codesandbox.io/s/4j4rqk2197

**Comment by thysultan** [comment]
Yes, we can add this.

**Comment by Blackglade** [comment]
Any updates on this? Just ran into this bug again.

**Comment by karlhorky** [comment]
@thysultan is this something easy to add? Maybe something about adding a new pattern here:  https://github.com/thysultan/stylis.js/blob/4561e9bc830fccf1cb0e9e9838488b4d1d5cebf5/stylis.js#L56-L84 and then creating a `case` below? Not sure if I'm following the code correctly...

**Comment by tulioliveira** [comment]
Hello! Is there any updates on this?

**Comment by karlhorky** [comment]
This is my super ugly hack for this until the bug is resolved:

```jsx
<head>
<style>
  {/*
    Hack for background-clip until problem with styled-components / stylis is solved:
      https://github.com/thysultan/stylis.js/issues/132
      https://github.com/styled-components/styled-components/issues/719#issuecomment-533898526
  */}
  {`
    .background-clip-text-hack {
      -webkit-background-clip: text;
    }
  `}
</style>
</head>
```

**Component:**

```jsx
<MyStyledComponent className="background-clip-text-hack"></MyStyledComponent>
```

Alternatively, if you had CSS Modules or something set up, you could also add the CSS via importing a CSS file.

I first tried it with inline styles (`style={{ WebkitBackgroundClip: 'text' }}`), but this didn't add the non-prefixed version correctly.

**Comment by Andarist** [comment]
This got implemented on the v4 branch

**Comment by karlhorky** [comment]
@Andarist any timeline for releasing v4? Would be cool to have this in `styled-components`:

https://github.com/styled-components/styled-components/issues/2237

**Comment by Andarist** [comment]
We are wrapping up the v4 - it's almost finished, but there is no hard ETA I could give you. The release schedule is our own, not tied to `styled-components`. Our API has changed dramatically, so it might not be possible for them to upgrade stylis within their current major version (unless introducing it as opt-in). For that, you would have to open an issue in their repository.

**Comment by karlhorky** [comment]
> Our API has changed dramatically

> To get more information about their POV, you would have to open an issue in their repository

Ok sure, is there any "upgrading" document that I can point them to to ask about their opinion about upgrading?

**Comment by Andarist** [comment]
Unfortunately not, the API is described roughly here: https://github.com/thysultan/stylis.js/tree/v4

**Comment by karlhorky** [comment]
Ok, I've asked whether they are open to upgrading to v4 here: https://github.com/styled-components/styled-components/issues/3060
