### ISSUE TITLE
Duplicate selector with plugin?

### ISSUE THREAD

**Issue by FezVrasta** [thysultan/stylis.js#137]
Hi, I'm trying to create a plugin that takes a selector and duplicates it.

So if I have:

```
.foobar:custom {
  color: red;
}
```

it should output:

```
.foobar:custom {
  color: red;
}
.foobar.custom {
  color: red;
}
```

I can't quite get how to do it reading the docs, may you point me in the right direction please?

Thank you

**Comment by Andarist** [comment]
Might not cover your use cases exactly (would be good to write tests for this), but it should look roughly like this:
```js
function extraScopePlugin(context, content, selectors, parents, line, column, length, type) {
  if (context !== 2 || type === 107) return

  let newSelectors = []

  for (let i = 0; i < selectors.length; i++) {
    let matched = false
    const tweaked = selectors[i].replace(/:custom/g, m => {
      matched = true
      return '.custom' 
    })
    if (matched) {
        newSelectors.push(tweaked)
    }
  }

  selectors.push(...newSelectors)
}
```

there is also probably better way to write this main loop, this is just a quick hack to show you how it might be done

**Comment by Andarist** [comment]
I hope you have figured out how to achieve your goal. The thread got stale though, without any recent activity - so I'm going to close it for now.
