### ISSUE TITLE
Support row-gap when prefixing

### ISSUE THREAD

**Issue by eramdam** [thysultan/stylis.js#138]
I'm using stylis through styled-components, and noticed that it doesn't auto-prefix the `row-gap` property to `grid-row-gap`.

> [CSS Grid Layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) initially defined the `grid-row-gap` property. This prefixed property is being replaced by `row-gap`. However, in order to support browsers that implemented `grid-row-gap` and not `row-gap` for grid, you will need to use the prefixed property as in the interactive example above.

This is problematic as (per [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/row-gap#Support_in_Grid_layout)), some "older" browsers only support the old `grid-row-gap`:

- Chrome 57 downwards
- Firefox 52 downwards
- Edge 16 downwards
- Opera 44 downwards
- Safari 10.1 downwards

**Comment by thysultan** [comment]
This is related to [https://github.com/thysultan/stylis.js/issues/119](https://github.com/thysultan/stylis.js/issues/119) vendor prefixing for grids in general.
