### ISSUE TITLE
Add support for replacing #rgba with rgba(rr, gg, bb, aa)?

### ISSUE THREAD

**Issue by Simon-Tang** [thysultan/stylis.js#142]
I hope this isn't out of scope for stylis, but would there be interest in adding the functionality of replacing RGBA hex colors with the `rgba(r,g,b,a)` equivalent, for compatibility with browsers including MS Edge?

**Comment by ekfuhrmann** [comment]
I second this as it's incredibly helpful for passing color variables into rgba().

**Comment by Andarist** [comment]
This is rather out of the scope of the core stylis - but it should be possible to write a plugin for it that would be able to do such a conversion for you. You can take a look at example plugins here:
https://github.com/thysultan/stylis.js/tree/4561e9bc830fccf1cb0e9e9838488b4d1d5cebf5/plugins
