### ISSUE TITLE
Support Browserslist

### ISSUE THREAD

**Issue by fabb** [thysultan/stylis.js#143]
It would be awesome if Stylis could support [browserslist](
https://github.com/browserslist/browserslist) to control which vendor prefixes to generate.

**Comment by Andarist** [comment]
I believe that this is out of the stylis scope - it's meant to be a minimal implementation. You could implement your own. With current v3 you can customize which properties are being prefixed by providing a function as `prefix` option as described here:
https://github.com/thysultan/stylis.js/tree/4561e9bc830fccf1cb0e9e9838488b4d1d5cebf5#vendor-prefixing
And with upcoming v4 you will be able to build such an integration yourself as well (taking provided prefixer as an example).

**Comment by Grawl** [comment]
If Stylis don't want to integrate Autoprefixer runtime, you can generate code using it to bundle. Just noticed I have vendor prefixes for flexbox including `-ms-flex-pack`.
