### ISSUE TITLE
CSS Grid Autoprefixing Support

### ISSUE THREAD

**Issue by collegeimprovements** [thysultan/stylis.js#145]
Hi Team,

There is an [issue](https://github.com/thysultan/stylis.js/issues/119) related to auto-prefixing for `css-grid`.
What is the current workaround currently? 
Should we refrain from writing any css-grid ?
Or `Stylis` is going to support css-grid at some point of time in future ?

**Comment by pjaws** [comment]
@collegeimprovements Use PostCSS/Autoprefixer instead, I guess.

**Comment by Andarist** [comment]
Duplicate of #119
