### ISSUE TITLE
Single quote broken execution

### ISSUE THREAD

**Issue by lksilva** [thysultan/stylis.js#147]
I found a error into styled-components lib and discovered that styled-components use stylis to proccess css and there is a bug when use a single quote, the style not is applied and broken in all places that use styled-component.

```js
const TopContainer = styled.div`
  min-height: 175px'
`;
```

I think that when this error to happen throw a error.

For better explanation https://github.com/styled-components/styled-components/issues/2618

**Comment by lucasraziel** [comment]
How can you be sure that this error is being caused by single quote?

**Comment by lksilva** [comment]
Because when quote is removed the application works properly

**Comment by Andarist** [comment]
This is not a valid input so it doesn't seem to make much sense for me to handle it here. What would you expect to happen?

**Comment by thysultan** [comment]
It is important to note that css doesn't throw errors when malformed css is encountered, and in the spirit of being fast we follow in those footsteps, stylelint is a good alternative to catch these kinds of errors.
