### ISSUE TITLE
`>` and `+` with `&` don't add scope

### ISSUE THREAD

**Issue by wmertens** [thysultan/stylis.js#149]
I would expect this to be sufficient to style a neighbor:

```
   + & { color: red; }
```

(it works when you do `.foo` instead  of `&`)

It turns out to have to be
```
  & + & { color: red; }
```

**Comment by thysultan** [comment]
Using the following on https://www.sassmeister.com/

```css
html {
  & + & { color: red; }
  + & { color: red; }
}
```

yields the following:

```js
html + html {
  color: red;
}

+ html {
  color: red;
}
```

Do you know of any preprocessors that follow the mentioned heuristic?

**Comment by wmertens** [comment]
The only preprocessor I know is Stylis ;)

```
html {
  & + & { color: red; }
  + & { color: red; }
  + .foo { color: red; }
}
```
yields
```
tml + html {
  color: red;
}
+ html {
  color: red;
}
html + .foo {
  color: red;
}
```

I'd say that's inconsistent?

**Comment by thysultan** [comment]
Not sure i understand you, stylis is consistent with sass.

**Comment by wmertens** [comment]
ah ok, I didn't know that's the gold standard. I think it's weird that `+ &` becomes invalid CSS but `+ .foo` is valid in sass, but if the idea is to be bug-for-bug compatible with sass this can be closed :)

**Comment by thysultan** [comment]
This is an intentional feature in sass. For example:

```css
.buton { color: blue; p & { color: red } }
```

Styles the button text color as red when it is within a paragraph.

**Comment by wmertens** [comment]
sure, but

```sass
.button { color: blue; + & { color: red } }
```

results in invalid CSS, it should make the button red if it follows another button.

**Comment by thysultan** [comment]
Yes, you have the following to archive that:

```js
.button { color: blue; & + & { color: red } }
```

However `.button { color: blue; p & { color: red } }` wouldn't work if you changed the heuristic to give more credence to `button { color: blue; + & {} }`  that is `.button { color: blue; p & { color: red } }` would result in `.button p .button { color: red }` which is valid css but doesn't archive the desired selector of a button within a paragraph.
