### ISSUE TITLE
LICENSE file should be included in stylis-rule-sheet npm bundle

### ISSUE THREAD

**Issue by nappy** [thysultan/stylis.js#157]
The license text is currently not provided with the `stylis-rule-sheet` npm bundle.
In order to allow automation tools like `license-webpack-plugin` to pick it up, it should be included there.
Also the license states: The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
This includes the npm registry.

**Comment by Andarist** [comment]
This plugin won't receive any new releases, Stylis v4 is around the corner and we'll make sure that LICENSE is included correctly in that release.
