### ISSUE TITLE
trying v4

### ISSUE THREAD

**Issue by leeoniya** [thysultan/stylis.js#183]
hey @thysultan, @Andarist 

just FYI, i'm gonna give v4 a try by converting uPlot.css [1] to a nested format. context: https://github.com/leeoniya/uPlot/issues/113.

will report any bugs. api looks super straight-forward:

```js
const { compile, serialize } = require("./stylis.cjs.js");
let css = serialize(compile(`.foo {color: red;}`));
```

i made my own rollup build cause your dev-dep `rollup-plugin-size` (ironically) is 2.24MB [2], while using node's native `const zlib = require('zlib');` is 0 bytes.

since we're all micro-lib fanatics, you guys might be interested in another project of mine: https://github.com/leeoniya/dropcss

cheers!

[1] https://github.com/leeoniya/uPlot/blob/master/src/uPlot.css
[2] https://packagephobia.now.sh/result?p=rollup-plugin-size

**Comment by Andarist** [comment]
Cool, hope you like it :) uPlot looks interesting, need to bookmark it for future reference.
