### ISSUE TITLE
Attribute selectors with no value cause TypeError

### ISSUE THREAD

**Issue by hamlim** [thysultan/stylis.js#19]
Using attribute selectors without a value `[data-attribute]` causes an error in stylis:

```
stylis.js:89 Uncaught TypeError: Cannot read property 'charCodeAt' of undefined

// [ attr selector
case 91: {
  // `[data-id=namespace]` -> ['data-id', 'namespace']
  attr = selector.substring(1, selector.length - 1).split('=');
  char = (namespace = attr[1]).charCodeAt(0); // Error occurs here
```

sample code:

```
const style = document.createElement('style');
style.textContent = stylis('[data-attribute]', 'color: red');
document.head.appendChild(style);
```

This happens with using `Stylis@2.0.10`.

This can be resolved when using `[data-attribute="anything here"]` however that enforces the element to have that value for the attribute, instead of matching every `data-attribute` instance no matter the value.

Might be possible to add a check to make sure there is an `=`, and if there is then split on it, else grab the value between index `1` and index: `length - 1` which would correspond to the `[` and `]` wrapping the data-attribute without a namespace.

**Comment by thysultan** [comment]
Thanks, v2.0.11 patches this.

**Comment by hamlim** [comment]
Awesome thanks for the quick response!
