### ISSUE TITLE
Lighthouse complains about old flexbox spec

### ISSUE THREAD

**Issue by 0x80** [thysultan/stylis.js#21]
When I run Lighthouse on my website it complains about old flex box spec being used. It doesn't like for example `display: webkit-box`. 

Is this something that could be configurable if you don't need to support really old browsers?

**Comment by thysultan** [comment]
[V3](https://github.com/thysultan/stylis.js/tree/master/rewrite#prefix) it supports turning off prefixing so you could use that when it's released.

**Comment by 0x80** [comment]
Would that turn things off completely or does it allow for partial prefixing based on a database like caniuse similar to postcss autoprefixer?

**Comment by thysultan** [comment]
It's an on/off option. What are all the properties that Lighthouse complained about?

**Comment by thysultan** [comment]
You can turn of prefixing in V3. I'm still open to case by case conditional prefixing but am unsure how such an API would work. Closing this, but we can continue to discuss here if you have some ideas.

**Comment by 0x80** [comment]
@thysultan Thanks. I'm afraid I can't be of much help for that either.

It was complaining only about the use of old flexbox properties. But Lighthouse seems to ignore it now 😕. Maybe they've updated the tests. The webkit-box properties are clearly still in my css.
