### ISSUE TITLE
Is this package still supported? https://www.npmjs.com/package/stylis-mixin

### ISSUE THREAD

**Issue by mpkelly** [thysultan/stylis.js#216]
As the title says, I'd like to use mixins on my project and don't care much about the format so long as I can support reusable chunks of CSS in some way. I found this npm package but there's no docs and links point back to here.

**Comment by Andarist** [comment]
This is a plugin compatible with v3 and we have released v4 recently which has no support for this. You could write a plugin like this for v4 though.

I'm not sure though what's the advantage as you can just JS to generate such reusable chunks of CSS so there is no need for mixins-like syntax to be included in Stylis.

**Comment by mpkelly** [comment]
Hi @Andarist, 

OK, thanks for the reply. In fact, I am using template strings but for my plugin-based project I wanted to keep the style for each plugin in its own css file. The only issue with this is the duplication. Is the source for that npm package available? Maybe I could make a plugin which I presume is simple enough? Also, do you know of any VS Code extensions that support Stylis's base CSS syntax and nothing more - basically css with selector nesting? This was another reason for the separate file, proper code highlighting and ideally linting if possible.

Mike

**Comment by Andarist** [comment]
> Is the source for that npm package available?

https://github.com/thysultan/stylis.js/blob/v3.5.4/plugins/mixin/index.js

> Maybe I could make a plugin which I presume is simple enough?

Shouldn't be that hard, I would recommend checking out existing plugins for v4 to get a better feeling how this can be done:
https://github.com/thysultan/stylis.js/blob/9b10fed6f0bb88eff2ba1a259583226279a91312/src/Middleware.js

> Also, do you know of any VS Code extensions that support Stylis's base CSS syntax and nothing more - basically css with selector nesting?

I doubt this, you could possibly trick this https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components to highlight syntax by adding:
```
const css = ([styles]) => styles 
```
and using it like:
```
css`
  color: hotpink;
`
```

**Comment by Andarist** [comment]
Hope this has helped you - if you have any other questions please just open a new issue.
