### ISSUE TITLE
Can you use asynchronous effects from middleware?

### ISSUE THREAD

**Issue by UpperCod** [thysultan/stylis.js#217]
Hi, I'm implementing stylis@4.0.0(the most amazing version of all), in this project I need to build unique css imports and that these in turn can import more css.

I have solved this in the following with stylis, eg:

```css
@import "./a.css";
@import "./b.css";
body{...};
```

```js
export async function readCss(file, imports = {}, returnRules) {
  const { dir } = path.parse(file);
  const code = await readFile(file); // asynchronous for reading the file

  let rules = await Promise.all(
    compile(code).map(async (child) => {
      if (child.type.trim() == "@import") {
        let value = child.value.trim().replace(
          /@import\s*(?:|\"|\')([^\"\']+)(?:|\"|\');/,
          "$1"
        );
        let file = path.join(dir, value);
        // prevents reading of already explored modules
        if (!imports[file]) {
          imports[file] = true;
          return readCss(file, imports, true); // recursion to complete the reading of one or more css modules
        } else {
          return [];
        }
      }
      return child;
    })
  );

  rules = rules.flat();

  if (returnRules) {
    return rules;
  }
  return serialize(rules, stringify);
}
```
My question is: **Can this behavior be applied with middleware?**

**note**: I'm forced to use `trim()`, to clear the reading of `.type`, since it can contain `\r`.

**Comment by Andarist** [comment]
> My question is: Can this behavior be applied with middleware?

It might be with a custom `serialize` that would support async processing, but you'd have to write it on your own. The problem might be though that serialization is recursive and introducing async contaminates the whole thing with, well, async logic so most likely an async alternative to `stringify` would also be needed to make it work.

I would stick to your solution though - it's easy enough and from the perf perspective I don't expect it would matter for you to process async operations while serializing.

> note: I'm forced to use trim(), to clear the reading of .type, since it can contain \r.

I've confirmed that this might happen by feeding `@import\r "./a.css";` into `compile` and this might be something we'd like to fix. Question is though - how `\r` became part of your input string at this position?

**Comment by thysultan** [comment]
Given that you can hold onto the AST after `compile`. You can also serialize the AST after all imports have resolved. i.e the first pass just initiates the import fetches then when resolved the second part serializes the output.

If you wanted to get fancy you could create a serializer that throws(like React suspense) when it encounters an import and resumes after the import has resolved....etc

**Comment by Andarist** [comment]
> Given that you can hold onto the AST after compile. You can also serialize the AST after all imports have resolved. i.e the first pass just initiates the import fetches then when resolved the second part serializes the output.

I believe that is exactly what @UpperCod is using now and I believe it's the best solution for this really (without adding too much complexity).

As to `\r` - I've created a PR fixing the issue: https://github.com/thysultan/stylis.js/pull/218

**Comment by UpperCod** [comment]
Thanks for your responses, the code is formatted with prettier this by default adds the `\r`.

> I believe that is exactly what @UpperCod is using now and I believe it's the best solution for this really (without adding too much complexity).

My times with Postcss + Rollup exceed 700 ms, now with Stylis + Rollup everything turns out in 20ms approx, I will try to materialize this in a plugin for rollup

With this I close the issue, Thanks!
