### ISSUE TITLE
Styles out order when using ampersand (&)

### ISSUE THREAD

**Issue by stonebk** [thysultan/stylis.js#219]
While investigating a bug while using styled-components (https://github.com/styled-components/styled-components/issues/3147), I came across this:

```
div {
    & {
        color: red;
    }
    color: blue;
}
```

I would expect the blue rule to come after the red rule, but it looks like it is output before?

![Screen Shot 2020-05-19 at 8 31 33 AM](https://user-images.githubusercontent.com/1432010/82346706-a7afe000-99ab-11ea-9454-9b6560c62a00.png)

**Comment by thysultan** [comment]
This is how sass/scss also works. The red comes after the blue because it is a child of & which is a child of the div while the blue is a direct child of the div.

**Comment by stonebk** [comment]
But shouldn't `& {}` effectively work as a direct child?

**Comment by Andarist** [comment]
No - & is just replaced by „current selector”. It’s nothing more than that. It doesnt change on its own the specificity, nesting, or anything else

**Comment by stonebk** [comment]
So direct child rules will be in order with respect to themselves, but they will always come before any other child rules. And then the child rules will always be in order with respect to themselves, but always come after the direct child rules. Does that sound right?

![Screen Shot 2020-05-19 at 11 36 48 AM](https://user-images.githubusercontent.com/1432010/82365119-13527700-99c5-11ea-9bd9-f792195f5923.png)

In my head, I was thinking it would flatten the child if it was using `&`, but instead it just treats it as a nested child and creates a new rule and replaces the `&`.

**Comment by Andarist** [comment]
Yes, that’s pretty much it. We dont try to optimize the output to flatten any rules like this - its out of scope for a parser.

**Comment by zhangbenber** [comment]
> This is how sass/scss also works.

Hi @thysultan, Sass seems to be changing that behavior, and started to warn about this kind of usages starting from now. See the console of the [playground](https://sass-lang.com/playground/#eJwzNEzJLFOo5lIAAjUoDQLJ+Tn5RVYKRakp1mCxWi4k0aSc0lRrrloAqWIO+Q==).

Here's a [detailed explanation](https://sass-lang.com/documentation/breaking-changes/mixed-decls/) about the change. The new behavior follows the way that CSS working group prefers.

In my usage, I come up with the case as below:

```scss
.button {
  background: white;
  &:where(.primary) { background: blue; }
  background: red; // The line is appended by some other libraries such as `@mui/system` to apply custom styles
}
```

However, the `<button class="button primary">` does not apply the custom red style in the case. Except `&` and `:where()`, that patten also affects other nested rules that do not increase the specificity, such as `@media()`. It will be much better if we are going to follow the upcoming CSS specifications 😃

**Comment by Andarist** [comment]
CSS Nesting isn't officially part of the CSS spec, it's a working draft. Once it gets standardized, I expect we'll follow the suite and change the Stylis behavior too. It will be a breaking change though (!) so I wouldn't expect that change to happen quickly.
