### ISSUE TITLE
Props produce different output with ampersand on top-level node vs nested

### ISSUE THREAD

**Issue by ricokahler** [thysultan/stylis.js#222]
I was compiling something like the following:

```css
.foo {
  &.a {
    color: red;
  }
}

&.bar {
  color: blue;
}
```

What I noticed is that, when there is a nested expression under a rule, then `&.a` returns the `props` what I would expect it to return:

```js
{
  value: '&\f.a',
  root: null,
  parent: { /* ... */ },
  type: 'rule',
  props: ['.foo.a'], // 👈  this is what I expect ✅
  // ...
}
```

However, in the next rule, `&.bar` returns `props` without any indication of a parent.

```js
{
  value: '&\f.bar',
  root: null,
  parent: null,
  type: 'rule',
  props: ['.bar'], // 👈  this is not what I expect 🔴
  // ...
};
```

---

I understand that there is no parent and that's why it can't pull something but to me it seems strange that there isn't some sort of placeholder for this non-existent root.

I also acknowledge the work-around is to simply to wrap it in some random root class name but, I still thought I'd just bring this up. I might've missed something!

Thanks for this great lib!

**Comment by thysultan** [comment]
The `.parent` property points to the parent(`null` in this case). What would you expect to be there? The raw `&`?

**Comment by thysultan** [comment]
The docs site provides the namespace in the source code i.e `[namespace] {...body}`

**Comment by ricokahler** [comment]
Yeah I guess it's fine to say that top-level `&.bar` will compile to empty string + `.bar`. I'll just wrap with a root namespace like you did in the docs.
