### ISSUE TITLE
making a stylis plugin, access parent css properties

### ISSUE THREAD

**Issue by MeisterTea** [thysultan/stylis.js#225]
Hi, I am in the process of creating a plugin to fix the broken iOS flex implementation:

When there isn't enough space on the viewport, the flex containers shrink.
The problem is that on iOS, if you don't specify a minimum height, the children will shrink way too much.

I want to fix this issue with stylis plugins in styled-components

I managed to inject a `flex-shrink: 0;` property when the current property is `flex-direction: column;`.

I have two problems:
* I get 3 times the `flex-shrink: 0;` property for every item having a `flex-direction: column;`
* I need to ignore this behavior if the parent item doesn't have a `flex-direction: column;` property as adding `flex-shrink: 0;` on a component in a `flex-direction: row;` parent will make it squeeze out of the boundings of the parent.
Can I check the properties of the parent?

```js
const iosFlexDirectionColumnFix = (context, content, selectors, parents, line, column, length, type) => {
  if (context === 1) {
    if (content === 'flex-direction:column') {
      return 'flex-direction:column;flex-shrink:0;'
    }
  }
}
```

**Comment by Andarist** [comment]
It would be helpful if you could share the full code with examples of actual and expected outputs.

**Comment by MeisterTea** [comment]
Sure: https://l51c3.csb.app/

**Comment by MeisterTea** [comment]
If you checks this on a iOS device (or browserstack or equivalent) you can see that the two flex containers are overlapped because of the height property missing

**Comment by Andarist** [comment]
I understand there might be some styling issues present on iOS devices but I was also asking about examples of actual & expected outputs. It's hard for me to tell quickly what's not working as expected in that codesandbox - I would like to focus here in helping you to write your plugin, without really diving into why you need it and what kind of a bug it is intended to fixup. You have listed some of your requirements for this plugin but it would be easier for me to understand them if they would be presented together with expected outputs for given inputs.

**Comment by MeisterTea** [comment]
ohh you meant the wanted css output?

I want my node `CrushedContent` to be be injected with `flex-shrink: 0;` but only because the parent html node does include `flex-direction:column;` property.

Please tell me if it's not clear enough

**Comment by Andarist** [comment]
> I want my node CrushedContent to be be injected with flex-shrink: 0; but only because the parent html node does include flex-direction:column; property.

This is not possible. Stylis plugin has 0 knowledge about your actual HTML structure and its nodes. It's just a string to string converter.

**Comment by MeisterTea** [comment]
ok, thank you
