### ISSUE TITLE
--dynamic css

### ISSUE THREAD

**Issue by thysultan** [thysultan/stylis.js#23]
This is an idea i've been thinking about... since stylis can identify css variables / a css-variables-like syntax for free it could potentially also mark them for faster re compiling of just the dynamic parts that a CSS in JS library can use to plugin into. For example: with s-c.

```js
const Button = styled.button`
color:red;
width: ${value};
`
```

The s-c library could then pass this to stylis as

```js
// first tell stylis to enable this option
stylis.set({dynamic: true})

// then pass as a string once
stylis('#id', `
color:red;
// prefixed the dynamic value with a hash
width: --hash1203 30px; 
`)
```

stylis would compile this to the following but also record that --hash1203 is a dynamic value that i can quickly recompile later when requested.

```css
#id {
color:red;
width: 30px;
}
```

s-c could then call stylis to re-compile only the dynamic parts if it has any in cache into a function when needed.

```js
stylis.pipe(hash, fn)
```

The fn `function` would receive only the parts that have changed

```
const fn = (selector, property, value, index) => {
style.insertRule(`${selector} { ${property}: ${value} }`, index)
}
```

This is an idea that could go into [V3 of the stylis rewrite](https://github.com/thysultan/stylis.js/tree/master/rewrite) i'm working on while still maintaining the small 3kb bundle size.

cc @geelen, @philpl, @mxstbr, @giuseppeg in case this is something they might see using.

**Comment by philpl** [comment]
Currently I'm replacing interpolations with placeholders and solid the resulting CSS at the same positions after stylis has flattened it.

The problem is that we need to be able to flatten CSS with interpolations that contain functions

In SC v3 @geelen and I would like to move this preprocessing logic into the main repo, so that we only have to use stylis once over the life cycle of a Styled component. This has the advantage that we can easily pull this logic into a babel plugin, while keeping this code in the core library. Furthermore it allows us to split static CSS out in the core library as well.

It'd be great to have a really stable foundation for this in stylis. However, we can make it work really efficiently as is.

If you decided to go ahead with this, there's unfortunately a lot to consider: dynamic classnames, an efficient intermediate structure, function interpolations, etc

I'd be happy to discuss it though :)

**Comment by giuseppeg** [comment]
> Currently I'm replacing interpolations with placeholders and split the resulting CSS at the same positions after stylis has flattened it.

We do this same thing in styled-jsx

> Furthermore it allows us to split static CSS out in the core library as well.

This could be done by Stylis (I think) which could split by "dynamic placeholders".
dynamic interpolations can only be functions whereas other kind of interpolations are static.

```js
`div { 
  background-color: ${color};
  color: ${(props) => props.theme.color} 
}`
/*
`div { 
  background-color: %PLACEHOLDER_STATIC_0%;
  color: %PLACEHOLDER_DYNAMIC_0% 
}` 
*/
```

Imho the best approach would be [glam's one](https://github.com/threepointone/glam) from @threepointone

**Comment by thysultan** [comment]
Sure, it could work; As long as the dynamic parts can be represented as a unique hash suffixed with some identifier stylis could pick this up for re-compiling the dynamic parts when requested ex.

```
// declaring dynamic properties
width: ${value} identifier hash; // template
width: 40px **hash; // passed
width: 40px; // what it generates the first time

// declaring dynamic selectors/blocks scopes
${value} identifier hash {...} // template
.selector **hash {...} ... // passed
.selector {...} // what it generates the first time
```

subsequent request could just return the parts that are dynamic that could be used to pipe into a CSSRuleList object or update a SSR <style> payload, though i'm unsure how the result should be consumed. i.e

```js
const fn = (selector, block, property, value, index) => {
style.insertRule(`${selector} { ${property}: ${value} }`, index)
}

stylis.pipe(hash, newValue, fn)

var updatedRule = stylis.compile(hash, newValue)

// or ?
```

**Comment by geelen** [comment]
Not sure I follow, are you suggesting converting the following syntax:

```js
const Button = styled.button`
  color: red;
  width: ${props => props.value};
`
```

Into this:

```css
/* Added and never touched */
.some-hashed-class {
  color: red;
  width: var(--some-hashed-var);
}
/* This gets insertRuled to set the interpolations */
.some-hashed-class { --some-hashed-var: 30px; }
```

Obviously, having two `Button`s with different `value`s would be the problem. You could, however, do this:

```
<Button value="30px"/>
// <button class="some-hashed-class" style="--some-hashed-var: 30px;"/>
```

And then never `insertRule` at all. But then, I'm not sure what that buys you necessarily. In SCv2 you can do:

```js
const Button = styled.button.attrs({
  style: props => ({ width: props.value })
})`
  color: red;
`
```

which was added to deal with rapidly-changing CSS properties. If a component only has one or two variants, I think cloning the whole CSS block and adding multiple classes is fine.

**Comment by thysultan** [comment]
@geelen It would return static css

```css
/* Added and never touched */
.some-hashed-class {
  color: red;
  width: 30px: // static value from ${props => props.value}
  ... // more rules
}
```

You'd however be able to subsequently recompile/retrieve only the parts that are dynamic for a given hash, this part –

```css
.some-hashed-class { width: 30px; }
```
or more specifically the different parts of the dynamic context

```js
{
selector: '.some-hashed-class',
property: 'width',
value: '30px',
context: '.some-hashed-class { width: 30px; }',
index: 12
}
```

Which could be used to make a granular update

```js
CSSStyleSheet.rules[12].style.width = '30px'
```

Though this won't add much unless there are more than a few dynamic variants, but the idea is to retrieve and in some way return the dynamic allocations in the context they where declared to be used in some form later, it could be in the form of a key-value pair or a function call with the data as arguments.

**Comment by geelen** [comment]
Oh right you weren't thinking of using css variables at all, just a similar syntax?

**Comment by thysultan** [comment]
Yes, it could be any invalid css syntax though.

**Comment by geelen** [comment]
Gotcha. Yeah I was chatting with @kof at JSConf about this api, but I'm still not sure it buys you that much, since it's only useful if every component with `.some-hashed-class` wants that change at the same time. So it might not be useful for SC, but it's still an interesting idea.
