### ISSUE TITLE
latest CDN is broken

### ISSUE THREAD

**Issue by malcome** [thysultan/stylis.js#230]
GOOD! <script crossorigin src="https://unpkg.com/stylis@4.0.0">

GOOD! <script crossorigin src="https://unpkg.com/stylis@4.0.1">

BAD(;-<) <script crossorigin src="https://unpkg.com/stylis@4.0.2">
message:
Refused to execute script from 'https://unpkg.com/stylis@4.0.2/dist/stylis.cjs' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

Thanks!

**Comment by thysultan** [comment]
Yes this is an issue with unpkg.com, have filled a report to see if it's possible to fix it on their end.

https://github.com/mjackson/unpkg/issues/268

**Comment by thysultan** [comment]
fixed by latest pkg.json changes.
