### ISSUE TITLE
v4 strips comments out by default

### ISSUE THREAD

**Issue by probablyup** [thysultan/stylis.js#236]
https://github.com/thysultan/stylis.js/blob/master/src/Serializer.js#L29

I'm trying to figure out how to implement cssjanus against v4 and since the noflip comment directives are stripped by `stringify`, I'm not really sure how to proceed.

This is what I have so far:

```ts
import cssjanus from "cssjanus";
import { compile, RULESET, stringify } from 'stylis';

function stylisRTLPlugin(element: Object, index: number, children: Object[], callback: Function): ?string {
  if (element.type === RULESET) {
    element.children = compile(cssjanus.transform(stringify(element, index, children, callback)))[0].children
  }
}
```

This works for everything except the presence of `/** @noflip */`

**Comment by Andarist** [comment]
1. Implement custom stringify based on the builtin one
2. Handle flipping on property level - is transform the whole exposed API from the cssjanus? Ideally u wouldnt have to stringify nodes to do such manipulation. U probably shouldnt assign a string to ruleset’s children - if u want to just provide the final stringified value for a particular node then assign it to the return property

**Comment by thysultan** [comment]
```js
if (element.type === COMMENT) {
return '/*comment*/'
}
```

stringify is just as much a middleware as `stylisRTLPlugin` so you can return what ever you want for comments.

**Comment by probablyup** [comment]
This is what I ended up settling on which seems to work https://github.com/styled-components/stylis-plugin-rtl/blob/3e19817d4da20800533ae19e4744c8a05989be81/src/stylis-rtl.js
