### ISSUE TITLE
Update Stylis in PostCSS benchmark

### ISSUE THREAD

**Issue by ai** [thysultan/stylis.js#240]
Hi. I was n able to update `preprocessors` and `prefixers` benchamarks in [`postcss/benchmark`](https://github.com/postcss/benchmark) because of the ck of the docs.

Can you help me with it to promote your awesome parser?

**Comment by thysultan** [comment]
Yes, i think it's missing the serialize to string step: The compile function itself only returns the AST.

```js
import {serialize, compile, stringify} from 'stylis'

var ast = compile(`h1{all:unset}`)
```

```js
import {serialize, compile, stringify} from 'stylis'

var string = serialize(compile(`h1{all:unset}`), stringify)
```


and prefixing is done as follows:

```js
import {serialize, compile, prefixer, stringify} from 'stylis'

var string = serialize(compile(`h1{all:unset}`), middleware([prefixer, stringify]))
```

**Comment by ai** [comment]
Thanks. Fixed.

**Comment by thysultan** [comment]
That was fast(pun intended).

<img width="540" alt="Screen Shot 2020-09-16 at 1 18 20 AM" src="https://user-images.githubusercontent.com/810601/93270838-9096c880-f7ba-11ea-82fa-e851955f7c2f.png">
