### ISSUE TITLE
ERR_REQUIRE_ESM error from requiring stylis

### ISSUE THREAD

**Issue by rcreagha** [thysultan/stylis.js#247]
I have a web app that uses emotion, which depends on stylis. While updating some dependencies I started getting the error seen below. The issue seems to be specific to 4.0.4, when I use 4.0.3 everything works fine.

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: myApp/node_modules/stylis/dist/stylis.js
    require() of ES modules is not supported.
    require() of myApp/node_modules/stylis/dist/stylis.js from myApp/node_modules/@emotion/babel-plugin/dist/emotion-babel-plugin.cjs.dev.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
    Instead rename stylis.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from myApp/node_modules/stylis/package.json.

      at Object.<anonymous> (node_modules/@emotion/babel-plugin/dist/emotion-babel-plugin.cjs.dev.js:16:14)
```

**Comment by Andarist** [comment]
This is weird - you should be loading this:
https://github.com/thysultan/stylis.js/blob/99afc806acf31a2b9a82d2d5439bba819e35eca6/package.json#L17
over this:
https://github.com/thysultan/stylis.js/blob/99afc806acf31a2b9a82d2d5439bba819e35eca6/package.json#L12

Could you prepare a runnable repro case? Sharing your node version etc could be helpful too.

**Comment by eidietrich** [comment]
Also seeing this error today, with Node v12.16.1. Reverting to 4.0.3 also fixed the problem for me.

**Comment by Andarist** [comment]
@eidietrich could you prepare a repro case on which I could take a look at?

**Comment by thysultan** [comment]
@Andarist might this be relevant to https://github.com/thysultan/stylis.js/pull/241#issuecomment-727255242

**Comment by belgattitude** [comment]
I can confirm the latest 4.0.4 packaging broke our app.

Context: it's a yarn workspace monorepo with nextjs + emotion (@emotion/babel-plugin..)

For those who are lucky enough to not rely on previous versions (like ^3.0 - a `yarn why stylis` will help to see) a quick hack is to force a module resolution in package.json

```
  "resolutions": {
    "stylis": "4.0.3"
  }
```

I'm trying to figure out a workaround, but crossing my fingers to have a fixed release asap. 

Not sure I can help fixing this in the stylis codebase, but I'll have a try.

**Comment by Andarist** [comment]
`stylis@4.0.5` has been released and it should resolve this problem. Updating your node version should also fix the problem.
