### ISSUE TITLE
browser support

### ISSUE THREAD

**Issue by fehmi** [thysultan/stylis.js#255]
Did you guys find a chance to test it? That would be great if you can specify in readme.

**Comment by Andarist** [comment]
https://stylis.js.org/ is literally using Stylis in the browser through unpkg CDN:
```html
<script type="module">
  import {compile, serialize, middleware, prefixer, stringify} from 'https://unpkg.com/stylis?module'
</script>
```

**Comment by fehmi** [comment]
I mean IE, Safari, Opera etc :)

**Comment by Andarist** [comment]
it works in all of them

https://unpkg.com/stylis@4.0.6/dist/umd/stylis.js

**Comment by fehmi** [comment]
Thanks
