### ISSUE TITLE
Patch release needed

### ISSUE THREAD

**Issue by sqal** [thysultan/stylis.js#256]
Hi @thysultan 

Could you release a new patch version that includes fix https://github.com/thysultan/stylis.js/commit/7fa14f99eb8e4c6f7f298e9fc47eef95b72f7740. It has been a while since this PR was merged and it would be great if the author of @emotion could fix the regression in his project but we need a version bump. Thank you :)

**Comment by thysultan** [comment]
Done! 4.0.7 published
