### ISSUE TITLE
prefixer middleware does not copy element type

### ISSUE THREAD

**Issue by probablyup** [thysultan/stylis.js#262]
When running `prefixer` over an element node like a keyframes object, the prefixed version is created but `element.type` is not set to `"@keyframes"`, it gets set to an empty string

**Comment by thysultan** [comment]
Example code?

**Comment by probablyup** [comment]
```ts
import { compile, Middleware, middleware, prefixer, serialize, stringify } from 'stylis';

const stylis = (css: string, extraPlugins: Middleware[] = []) =>
  serialize(compile(css), middleware([...extraPlugins, stringify]));

stylis(
  `@keyframes a {
    0% { left: 0px; }
    100% { left: 100px; }
  }
`,
  [prefixer]
)
```

If another middleware is added after `prefixer` the new keyframe rule generated by the `prefixer` plugin has `element.type` set to empty string instead of `"@keyframes"`

**Comment by Andarist** [comment]
Just a note about the current implementation - the third argument passed here is for the `type` and it is set to `''`:
https://github.com/thysultan/stylis.js/blob/e6843c373ebcbbfade25ebcc23f540ed8508da0a/src/Middleware.js#L48

Looking into the codebase - all calls to `copy` pass an empty string there.

**Comment by thysultan** [comment]
Pending accidental fix with the next patch i'm working on.
