### ISSUE TITLE
tokenize(): produces inconsistent results

### ISSUE THREAD

**Issue by layershifter** [thysultan/stylis.js#263]
Hey folks!

I am working on a plugin for `:global()` selector and using `tokenize()` there. I am not sure that it's a bug, but results are inconsistent:

```ts
tokenize(':global(body) .foo') 
// => [ ':', 'global', '(body)', ' ', '.foo' ]
//            👆 selector produces a single string
tokenize(':global([data-popper-placement]) .foo') 
// => [ ':', 'global', '([data-popper-placement])', ' ', '.foo' ]
//                      👆 selector produces a single string
tokenize(":global([data-popper-placement^='top'])")
// => [ ':', 'global', "([data-popper-placement^='top'", ']', ')' ]
//                                                       👆 closing bracket and a paren are separate strings
```

I also tried this string with `namespace` plugin:

```tsx
serialize(compile(`:global([data-popper-placement^="top"]) .foo { color: red }`), middleware([namespace, stringify]))
// => [data-popper-placement^="top]) .foo[object Object]{color:red;}
//                                ^ brackets are closed properly ✔
//                                  ^ but "[object Object]" is definitely an issue ❌
```

Can you please clarify if it's a bug in tokenizer?

**Comment by thysultan** [comment]
The last one looks like a bug, not sure about the others, will look into it.

**Comment by layershifter** [comment]
@thysultan were you able to check if it is a bug? 😊

**Comment by thysultan** [comment]
The last one was a bug(fixed now on the latest patch), the rest you can manually recursively tokenize to get the desired depth of tokens.

**Comment by thysultan** [comment]
The last one was a bug(fixed now on the latest patch), the rest you can manually recursively tokenize to get the desired depth of tokens.
