### ISSUE TITLE
column is incorrect

### ISSUE THREAD

**Issue by jantimon** [thysultan/stylis.js#269]
Hi :)

I am trying to integrate stylis.js into https://astexplorer.net/ and it looks quite promising however it seems like that all column values are wrong (or I don't understand what column means).

In the following example I would expect line: 1 column: 4

```css
    border: 1px solid black;
```

However it generates column 29:

![AST_explorer](https://user-images.githubusercontent.com/4113649/128007938-5f3189a4-95bd-4a09-b629-c740e5125d55.png)

**Comment by jantimon** [comment]
Thanks for your quick response

I guess we could also integrate it without positions.. In that case you might think about removing them..

Just out of curiosity - why is the column position amount to high? Couldn't we just store the column before it is incremented?

**Comment by thysultan** [comment]
column denotes where it ends: i.e `black;` at the semicolon. Rather than from the beginning `border`.
