### ISSUE TITLE
ReferenceError: escade is not defined

### ISSUE THREAD

**Issue by brunolemos** [thysultan/stylis.js#30]
I have no idea what `escade` is, but it's breaking my `react` application that uses `styled-components@master` (and has `stylis` as a dependency):

![image](https://cloud.githubusercontent.com/assets/619186/26768582/44f4a484-497f-11e7-85fd-5a1785da1f6d.png)

It was introduced on this commit: https://github.com/thysultan/stylis.js/commit/7c7ebe49637d3477988fadefa22b679ac95dd9cd

Could you prevent this by first checking if this variable exists or any other way?
Thanks.

cc https://github.com/styled-components/styled-components/pull/829

**Comment by thysultan** [comment]
typo, should be escape, patched in v3.0.16
