### ISSUE TITLE
Precompute calc when possible

### ISSUE THREAD

**Issue by corbanbrook** [thysultan/stylis.js#32]
When possible calc can be precomputed:

`calc(10px * 2)` => `20px`
`calc(100% / 3)` => `33.3333%`

This is done in many transpilers like stylus, less, postcss etc.

Not possible when dealing with relative values like:
`calc(100vh - 5px)`
`calc(50% - 20px)`

**Comment by thysultan** [comment]
This is possible. Is there any benefit to precomputing here? and are there any caveats i.e could `calc(100% / 3)` could have a greater deal of accuracy than `33.3333%`?

**Comment by corbanbrook** [comment]
Here is the calc plugin from postcss that goes into more detail about how a feature like this works:
https://github.com/postcss/postcss-calc

**Comment by thysultan** [comment]
Yes this can be done with [plugins](https://github.com/thysultan/stylis.js#plugins), i'd be happy to help out if you want to work on this.

**Comment by thysultan** [comment]
Created a [custom-properties](https://github.com/thysultan/stylis.js/tree/master/plugins/custom-properties) plugin as an example to how this can be done.
