### ISSUE TITLE
option to disable minification

### ISSUE THREAD

**Issue by giuseppeg** [thysultan/stylis.js#36]
It would be nice to be able to disable minification completely. This is useful for development mostly. Would it be hard to do so?

**Comment by thysultan** [comment]
As in preserve new lines and tabs? currently yes it might be hard to accomplish.

**Comment by giuseppeg** [comment]
yes, ok no worries. I just asked out of curiosity.

**Comment by thysultan** [comment]
Though if you just wanted to format/prettify the output i think a plugin can do that.

**Comment by thysultan** [comment]
Will experiment with this when i have time.

**Comment by akvadrako** [comment]
This isn't totally safe, because control characters inserted in literal strings will be modified. But I think it's the best that can be done with the current API:

```js
function stylisPluginPretty(context, content) {
    if(context != -2) {
        return
    }

    return content
        .replace(/{/g, ' {\n')
        .replace(/;/g, ';\n')
        .replace(/}/g, '}\n\n')
}
```
