### ISSUE TITLE
PrinceXML specific nested css selectors broken in the last week or so

### ISSUE THREAD

**Issue by arian-swydo** [thysultan/stylis.js#37]
Hello,

I'm using styled-components, which has a dependency on stylis. In their update 2.0.1 they upgraded stylis, and now my PrinceXML specific css stopped rendering correctly.

(PrinceXML generates PDF's from CSS/HTML/JS)

So previously I could do:
```
@page {
    @top-left {
        font-size: 11px;
        content: "this is an example string shown in the header";
    }
}
```
which is plain css, not pre-processed syntax or anything.

As of late, it completely ignores these selectors and prints out the cssRules outside of these selectors.

Any way to fix this?

**Comment by thysultan** [comment]
patched in 3.1.7
