### ISSUE TITLE
breaks on data uri

### ISSUE THREAD

**Issue by wmertens** [thysultan/stylis.js#4]
When using data uri's embedded in the css, it breaks stylis parsing.

Reproduction: http://jsbin.com/vetude/edit?js,output

I believe this causes https://github.com/styled-components/styled-components/issues/433

**Comment by thysultan** [comment]
Thanks, will push a patch for this.

**Comment by thysultan** [comment]
@wmertens pushed a patch for this in v1.0.1(supports quoted and non-quoted.), you can try to see if you can break it on the console of [https://rawgit.com/thysultan/stylis.js/master/benchmark/index.html](https://rawgit.com/thysultan/stylis.js/master/benchmark/index.html), i.e

```js
stylis(`.abc`, `
background-image: url(data:image/png;etc); /* quoting the url doesn't help */
`)
```

**Comment by wmertens** [comment]
👍 looks great, thanks for your swift response! 🎉
