### ISSUE TITLE
objectify plugin

### ISSUE THREAD

**Issue by barak007** [thysultan/stylis.js#42]
I saw that you started ast and objectify plugins. cool!

I took the idea and started my own.

here is the gist for it I want to get you feedback.

[gist](https://gist.github.com/barak007/7218c0ff0ae539c50f39a2466851797c)

**Comment by thysultan** [comment]
LGTM, only one nit that has probably crossed over from my impl: [L110](https://gist.github.com/barak007/7218c0ff0ae539c50f39a2466851797c#file-objectify-js-L110) should return/break.
