### ISSUE TITLE
Prefix column-count css property

### ISSUE THREAD

**Issue by roopemerikukka** [thysultan/stylis.js#43]
I'm using `column-count` css property in my css but the property doesn't get prefixed. I'm not quite sure what properties the library should prefix and what not to. Are you using browserslist or some predefined list of properties to prefix?

**Comment by thysultan** [comment]
>I'm not quite sure what properties the library should prefix and what not to.

Anything that has significant browser share.

>Are you using browserslist or some predefined list of properties to prefix?
I try to add them as i come across them.

I've actually added this for the next release, will release soon.

**Comment by thysultan** [comment]
Patch landed in 3.2.0
