### ISSUE TITLE
support autoprefixer for display: grid properties?

### ISSUE THREAD

**Issue by johhansantana** [thysultan/stylis.js#51]
Hello

I'm wondering if it's possible for [this](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/CSS_Grid_and_Progressive_Enhancement#The_Internet_Explorer_and_Edge_situation) to be implemented?

![image](https://user-images.githubusercontent.com/9933887/28642737-63e511a6-7221-11e7-983b-a3c6c14075e4.png)

**Comment by thysultan** [comment]
Yes, just as much as is possible [marginally](https://rachelandrew.co.uk/archives/2016/11/26/should-i-try-to-use-the-ie-implementation-of-css-grid-layout/), but i feel like the following is a warning that it would complicate things.

```
"...Unless your layout is very simple line-based placement, this is likely to cause you more problems that it solves. I would not suggest letting autoprefixer run on grid properties, and instead write a version using the IE version of Grid Layout, if it makes sense for you."
```

**Comment by johhansantana** [comment]
I see, I guess it should be used only when developing apps for clients that the audience are not using IE or Edge.

I wonder what could go wrong when prefixing the `-ms-` on simple layouts? I don't see why it could cause problems.

**Comment by thysultan** [comment]
I have yet to use grids but judging from [https://rachelandrew.co.uk/archives/2016/11/26/should-i-try-to-use-the-ie-implementation-of-css-grid-layout/](https://rachelandrew.co.uk/archives/2016/11/26/should-i-try-to-use-the-ie-implementation-of-css-grid-layout/), there doesn't seem to be a 1-1 path that would work for both implementations, and there are properties that are outright not supported by -ms- IE implementation and vice-versa.
