### ISSUE TITLE
Position fixed with wrong prefixing

### ISSUE THREAD

**Issue by evenchange4** [thysultan/stylis.js#53]
There are useless prefixing of `position: fixed` when I update from `3.2.9` to `3.2.10`:

```diff
// compare 3.2.9 with 3.2.10

+ position: -webkit-box;
+ position: -webkit-fixed;
+ position: -ms-fixedbox;
  position: fixed;
```

Online demo:

![2017-08-24 11 00 59](https://user-images.githubusercontent.com/1527371/29647424-a8d95db6-88bb-11e7-823a-281f5179ccfd.png)

**Comment by thysultan** [comment]
Pushed the patch in 3.2.11
