### ISSUE TITLE
Support autoprefixer for flex in IE10

### ISSUE THREAD

**Issue by 770580** [thysultan/stylis.js#60]
Please add prefixes for flexbox in IE10. Such as [here](https://msdn.microsoft.com/en-us//library/hh673531(v=vs.85).aspx).

**Comment by thysultan** [comment]
Stylis does prefix flexbox for IE10. Can you elaborate? Did you find something missing?

**Comment by 770580** [comment]
Yes, in IE 10 justify-content: space-between; should be -ms-flex-pack: justify;

**Comment by thysultan** [comment]
Is there any documentation i can look at regarding this. [Autoprefixer](http://autoprefixer.github.io/) also doesn't prefix this property.

**Comment by 770580** [comment]
Article on MSDN [Flexible box ("Flexbox") layout in Internet Explorer 10](https://msdn.microsoft.com/en-us//library/hh673531(v=vs.85).aspx)

**Comment by thysultan** [comment]
Patched in 3.2.16

**Comment by 770580** [comment]
Please, add prefix for align-self in IE 10, it also missed.

**Comment by thysultan** [comment]
Can you provide more details? What is it [now](http://stylis.js.org), what should it be?

**Comment by 770580** [comment]
IE 10 support the 2012 flexbox syntax. For `align-self` [official documentation](https://www.w3.org/TR/2012/WD-css3-flexbox-20120322/#flex-item-align).

**Comment by thysultan** [comment]
I think this is already supported [stylis.js.org](stylis.js.org) outputs the IE10 version `-ms-flex-item-align` for this property.

**Comment by 770580** [comment]
The name of the property is correct, but the values `flex-start and flex-end` for `align-self` in IE10 must be `start and end `.

**Comment by thysultan** [comment]
@770580 Patched in 3.2.17
