### ISSUE TITLE
Prefixing SVG fill unnecessarily

### ISSUE THREAD

**Issue by oliverjam** [thysultan/stylis.js#61]
It looks like the `fill` SVG property gets a webkit prefix it doesn't need, as it has the same first three letters as [filter](https://github.com/thysultan/stylis.js/blob/master/stylis.js#L961). The [MDN page](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill) doesn't mention this ever needing a prefix.

Happy to make a PR with a fix 😄

**Comment by thysultan** [comment]
Yes, please. [#L969](https://github.com/thysultan/stylis.js/blob/master/stylis.js#L969) is an example of how conflicts are handled.

**Comment by thysultan** [comment]
Published 3.2.19 with this patch.
