### ISSUE TITLE
Ability to select parent from children ?

### ISSUE THREAD

**Issue by kopax** [thysultan/stylis.js#7]
Is there a way like in [stylus](http://stylus-lang.com/) to select a parent from it's children ? (see https://davidwalsh.name/stylus-parent-selectors)

I have tried to add __&__ at the end but it didn't do anything.

**Comment by thysultan** [comment]
@kopax What did you try exactly(context)?

**Comment by thysultan** [comment]
For example 

```
.foo {
  h1 & {
    color: red;
  }
}

// produces

h1 .foo {color: red;}
```

and

```
foo & {
  color: red;
}

// produces

.foo ${namespace}
```

**Comment by kopax** [comment]
I am using [styled-components](https://github.com/styled-components/styled-components) `v2.0.0-5` which use stylis.

I am using [react-modal](https://github.com/reactjs/react-modal) which allow us to create a modal Component. This modal will be wrapped with an Overlay I don't really know how.

I want from within the Modal to select this Overlay which I know the class in advance by settings the `overlayClassName` property to my modal.

What I am trying to do : 

```jsx
class ModalUnstyled extends React.Component {
  render() {
    return (
      <Modal className={cn(this.props.className, 'modal-background')} overlayClassName="Overlay"><h1>Hello World</h1></Modal>
    )
  }
}

const Modal = styled(ModalUnstyled)`
  &.modal-background {
   background-color: #fff;
   .Overlay & {
      background-color: rgba(0, 0, 0, .5);
    }
  }

`
I believe there is no way to select the overlay, my mistake.

**Comment by thysultan** [comment]
You could do

```js
const Modal = styled(ModalUnstyled)`
  &.modal-background {
   background-color: #fff;
  }
  :global(.Overlay) {
     background-color: rgba(0, 0, 0, .5);
  }
```
