### ISSUE TITLE
Parser breaks browser specific targets in certain cases

### ISSUE THREAD

**Issue by mjsisley** [thysultan/stylis.js#71]
I'm running into some browser implementation differences, that requires some css hacks to target specific browsers. In a perfect world this wouldn't be needed... but I need them at the moment.

As some of these methods are hacks and not W3C compliant, they are being sanitized by styled-components, rendering them non-effective (injectGlobal or at the component level). An example would be the css-tricks method of targeting firefox (https://css-tricks.com/snippets/css/css-hacks-targeting-firefox/): `@-moz-document url-prefix() { .selector { color:lime; } }`. styled-components strips the brackets, making this into: `@-moz-document url-prefix().selector { color:lime; }` which has no effect.

Temporarily, I have resorted to using a separate css stylesheet where needed.

**Comment by thysultan** [comment]
Thanks, i'll look into this.

**Comment by thysultan** [comment]
Patched in 3.4.1
