### ISSUE TITLE
Autoprefix for IE10

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [thysultan/stylis.js#72]
Some properties are not autoprefixed properly yet

* `flex-grow` -> `-ms-flex-positive`
* `flex-shrink` -> `-ms-flex-negative`
* `flex-basis` -> `-ms-flex-preferred-size`
* `justify-content: space-between` -> `-ms-flex-pack: justify`

https://msdn.microsoft.com/en-us/library/hh673531(v=vs.85).aspx

Here's a listing of most of them:

https://gist.github.com/codler/2148ba4ff096a19f08ea#file-flex-less-L19-L65

**Comment by thysultan** [comment]
From testing this out, this one `justify-content: space-between` -> `-ms-flex-pack: justify` is currently prefixed as mentioned.

How can i reproduce your encounter?

**Comment by thysultan** [comment]
`-ms-flex-positive`, `-ms-flex-negative` and `-ms-flex-preferred-size` don't seem to be valid values but rather placeholders `<positive-flex> <negative-flex> <preferred-size>` for integer values used in the `flex` shorthand.

**Comment by evan-scott-zocdoc** [comment]
@thysultan `-ms-flex-positive, -ms-flex-negative and -ms-flex-preferred-size` they're definitely valid. I have a PR internally where I add them and it fixes all our IE10 layout issues. Specially if you use `flex-grow`,`flex-shrink`, and `flex-basis` etc without the shorthand.

**Comment by evan-scott-zocdoc** [comment]
You know what, I think there might be an issue in styled-components related to the dependency version.

![screen shot 2017-11-06 at 4 29 54 pm](https://user-images.githubusercontent.com/25586630/32464942-beeec0b2-c30f-11e7-9476-2d82bd2d6428.png)

Seems like it's pulling in an old version for some reason...

**Comment by thysultan** [comment]
Your right about `-ms-flex-positive, -ms-flex-negative and -ms-flex-preferred-size` i was looking at the shorthand values – will fix this in the next patch release, however `justify-content: space-between` should be working as expected since `3.2.16`. I'm not sure why npm is installing an older version.

**Comment by evan-scott-zocdoc** [comment]
Made a PR to try and handle the sc issue: https://github.com/styled-components/styled-components/pull/1296

**Comment by thysultan** [comment]
Patched in 3.4.1

**Comment by evan-scott-zocdoc** [comment]
@thysultan thank you, tried it out in my project and works perfectly!
