### ISSUE TITLE
New line problem

### ISSUE THREAD

**Issue by asistapl** [thysultan/stylis.js#74]
Hi!
I encountered a little problem with new lines in property values.
In this example semicolon is inserted too early in the string:

https://codepen.io/asistapl/pen/zPpZgr?editors=0012

It can be avoided by escaping new line sign but it's not very intuitive and looks bad.
When writing grid layout rules it's common to use multi line strings in property values so it would be great if it could be solved.

Thanks!

**Comment by thysultan** [comment]
Related to [https://github.com/thysultan/stylis.js/pull/56](https://github.com/thysultan/stylis.js/pull/56). 

It should work if you disable auto semi-colon insertion mode `stylis.set(semicolon: true)`. 

That said i do intend to improve the auto semi-colon insertion mode heuristics to take this into account.

**Comment by asistapl** [comment]
Thanks.
I'm using emotion so I don't have access to that setting.
I think they remove white space in tagged template literals but problem occurs when interpolating other strings where white space is preserved.

**Comment by thysultan** [comment]
Can you open an issue with emotion to disable ASI mode until this is fixed?

**Comment by thysultan** [comment]
Patched in 3.4.5
