### ISSUE TITLE
Vendor prefixes iOS 8

### ISSUE THREAD

**Issue by kullbros** [thysultan/stylis.js#76]
I am moving from styled-components 2.0.0 to 2.2.3 which uses stylis 3.x, but there is problem with missing vendor prefixes. For example on iOS 8 when using flex-basis, it should prefix it with -webkit-flex-basis.

**Comment by thysultan** [comment]
Can you post a repro of your find: input, expected, actual.

**Comment by kullbros** [comment]
Well it's private project, so I can't show it here. But the case is simple, try to use 'flex-basis: 100%;' and it should autoprefix it with '-webkit-flex-basis: 100%;'

**Comment by thysultan** [comment]
From the post it came of like you had other properties that where not being vendor prefixed... can you post them as well or was it just "flex-basis"?

**Comment by kullbros** [comment]
Sorry I didn't check others, but as I know also -ms-flex-basis was missing for flex-basis. So maybe the problem is just for this one.

**Comment by thysultan** [comment]
I'm confused since [http://autoprefixer.github.io/](http://autoprefixer.github.io/) produces

```css
-ms-flex-preferred-size: 100%; 
flex-basis: 100%;
```

Which is what [stylis](https://stylis.js.org/) also produces. 
Are you sure the `-webkit-` vendor prefix is a valid variant for `flex-basis`?

**Comment by kullbros** [comment]
Yes I'm sure, because it is working with this prefix, I tried it on browserstack. Without the prefix, flexbox is not rendered correctly on iOS 8.

**Comment by kullbros** [comment]
Check browser compatibility here https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis

**Comment by kullbros** [comment]
Btw, it would be nice to support something like this: https://www.npmjs.com/package/browserslist :)

**Comment by thysultan** [comment]
There a bit of conflicting info on this, mdn, mentions safari 7, other sources safari 6, what seems sure though is that safari 8 does support this which is what iOS 8 should be using. So i'm not sure why it doesn't work there. I'll look into it.

>Btw, it would be nice to support something like this: https://www.npmjs.com/package/browserslist

stylis is trying to be a small preprocessor(3kb) so it can't make prefixing configurable to that extent.

**Comment by kullbros** [comment]
Hmm, even https://caniuse.com/#search=flexbox says that Safari 8 needs prefix.

**Comment by thysultan** [comment]
Patched in 3.4.5

**Comment by kullbros** [comment]
Thank you for the fast fix, it's working now :)
