### ISSUE TITLE
More IE flex things

### ISSUE THREAD

**Issue by probablyup** [thysultan/stylis.js#77]
`align-content: flex-start` -> `-ms-flex-line-pack: start`
`align-content: flex-end` -> `-ms-flex-line-pack: end`

~~`align-self: flex-start` -> `-ms-flex-item-align: start`
`align-self: flex-end` -> `-ms-flex-item-align: end`~~

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Advanced_layouts_with_flexbox

**Comment by thysultan** [comment]
`align-self: flex-start;` and `align-self: flex-end;` seem to work as expected, what am i missing?

**Comment by probablyup** [comment]
Double checked and you're right - it's just `align-content` that needs tweaking
