### ISSUE TITLE
Bytes savings

### ISSUE THREAD

**Issue by Andarist** [thysultan/stylis.js#79]
I was playing around and I've wanted to check what would change if stylis would have constants inlined.

I've started from checking what is the actual gzipped size of the minified bundle and it is 4559. I don't know how to generate it, because you don't have any script in the repo for this task. I thought you were using google closure compiler so I've tried to use google-closure-compiler-js, but unfortunately it crashes (or I dont know how to use it) - "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory".

So I've used something that I know, uglifyjs@3, minified the stylis and checked its gzipped size to have some point of reference. It got slightly better result (although I dont know what I am comparing with really) - 4548.

I've inlined manually [all char codes and special identifiers](https://github.com/thysultan/stylis.js/blob/4cc510b4069993e3a5d01fe5c241a3a28f094b70/stylis.js#L89-L127) through out the file and run uglifyJS agains and checked the gzipped size again, which was 4353.

That's not bad, nearly 200 bytes of savings. And of course the inlining could be automated with Babel or something as compilation step.

I've also wanted to check benchmarks to see if that helps anything (I suppose it helps a little or does no change), but PostCSS benchmarks are crashing on stylis at the moment so I couldn't check it reliably.

Would you be interested in following this and possibly having me implementing this constants inlining through with a babel?

**Comment by mitchellhamilton** [comment]
Just wanted to mention that emotion ships a version of stylis that we run through closure compiler. I use the [online closure compiler](https://closure-compiler.appspot.com/home), enable advanced, paste in stylis and remove the last bit of the compiled code that is related to UMD. [It looks like this](https://github.com/emotion-js/emotion/blob/master/packages/emotion-utils/src/stylis.js)

**Comment by thysultan** [comment]
I used uglifyjs for the current minified distribution artifacts in the repo.

I haven't tested with the JavaScript version of closure compiler but i think the Java [version](https://closure-compiler.appspot.com/home) does this out of the box. which is one of the reasons the jsdocs and bracket notations where used – motivated by the need to support both the simple and advanced mode of closure compiler(java version).

Do you have a reproduction of the crashes on google-closure-compiler-js? Is it specific to only stylis?

**Comment by Andarist** [comment]
> Just wanted to mention that emotion ships a version of stylis that we run through closure compiler. I use the online closure compiler, enable advanced, paste in stylis and remove the last bit of the compiled code that is related to UMD. It looks like this



That's actually another topic that I would like to tackle here - I think `stylis` should ship es & cjs bundles (maybe event closure compiled?) to npm, so libraries like emotion could consume it gracefully without having to copy its source.

> I used uglifyjs for the current minified distribution artifacts in the repo.

Could you share which version of the uglifyjs did you use and what options have you used? Would be great to have this configured in the repository. But I guess what we'd really want it to configure this with google closure compiler.

> I haven't tested with the JavaScript version of closure compiler but i think the Java version does this out of the box.

I can confirm that (thanks to @mitchellhamilton providing the urls) google closure compiler is doing this inlining even in a simple mode.

> Do you have a reproduction of the crashes on google-closure-compiler-js? Is it specific to only stylis?

This was my first attempt at using google closure compiler. I've literally just installed it's js version through npm, got 20171203.0.0 version and it crashes using:
```
google-closure-compiler-js stylis.js > stylis.min.js
```

**Comment by thysultan** [comment]
>That's actually another topic that I would like to tackle here - I think stylis should ship es & cjs bundles (maybe event closure compiled?) to npm, so libraries like emotion could consume it gracefully without having to copy its source.

That would be great.

>Could you share which version of the uglifyjs did you use and what options have you used? Would be great to have this configured in the repository.

Local global copy, 3.0.28, `uglifyjs ${file} -o ${file_path}/${file_base_name}.min.${file_extension} --compress 'conditionals=false,if_return=false,booleans=false' --mangle --screw-ie8`.

**Comment by leeoniya** [comment]
in recent experience, while Closure produces significantly smaller bundles than Uglify, its aggressive inlining often hurts perf since huge functions will not get inlined by v8's JIT. for microlibs the perf loss can outweigh the size reduction.

i've moved domvm from Closure to Uglify in the past week. the gzip size remained practically the same (min size went up more). the perf boost was ~10%.

**Comment by Andarist** [comment]
> in recent experience, while Closure produces significantly smaller bundles than Uglify, its aggressive inlining often hurts perf since huge functions will not get inlined by v8's JIT. for microlibs the perf loss can outweigh the size reduction.

Interesting. I would love to measure the changes, but benchmarking is hard and I have no experience how to do that well to get reliable results, so the engine won't optimize away my iterations etc. As mentioned I've tried to use existing benchmark but it seems to crash on stylis at the moment.

But anyway inlining mentioned constants should not hurt perf in anyway (from what I know). Inlining functions is whole other topic.

**Comment by leeoniya** [comment]
i have this strange feeling *someone* in this thread has some bechmarking experience ;)

**Comment by thysultan** [comment]
>I've tried to use existing benchmark but it seems to crash on stylis at the moment.

@Andarist How can i reproduce this, do you have a link to the fork?

**Comment by Andarist** [comment]
@thysultan 
I've literally just cloned https://github.com/postcss/benchmark , installed deps with `yarn` and tried to use `npm run test`, which gives me:
```sh
> gulp

[01:29:38] Using gulpfile ~/Desktop/benchmark/gulpfile.js
[01:29:38] Starting 'default'...
[01:29:38] Starting 'lint'...
[01:29:39] Finished 'lint' after 628 ms
[01:29:39] Starting 'bootstrap'...
[01:29:39] Finished 'bootstrap' after 2.3 ms
[01:29:39] Starting 'preprocessors'...
[01:29:40] Running suite Bootstrap [/Users/mateuszburzynski/Desktop/benchmark/preprocessors.js]...
[01:29:46]    libsass x 9.55 ops/sec ±5.05% (29 runs sampled)
[01:29:52]    Rework x 17.32 ops/sec ±4.18% (46 runs sampled)
[01:29:58]    PostCSS x 26.23 ops/sec ±9.43% (69 runs sampled)
[01:30:04]    Stylecow x 4.92 ops/sec ±6.43% (29 runs sampled)
[01:30:11]    Stylus x 6.23 ops/sec ±21.01% (39 runs sampled)
[01:30:17]    Less x 8.58 ops/sec ±6.58% (47 runs sampled)

/Users/mateuszburzynski/Desktop/benchmark/preprocessors.js:190
                    if ( err ) throw stderr;
                               ^

npm ERR! Test failed.  See above for more details.
```

and from what I see stylis is next in line after Less, so I've assumed it crashes because of the stylis

**Comment by thysultan** [comment]
@Andarist I get a similar error, the problem comes from `Ruby Sass` and `Compass` both of which have ruby dependancies – that might be related to yarn not installing. It works if i comment out `Ruby Sass` and `Compass`.

**Comment by mitchellhamilton** [comment]
I just ran the postcss benchmarks but removed all the non stylis ones and added ones with stylis after closure compiler (i used the one we export from emotion-utils)  https://github.com/mitchellhamilton/postcss-benchmark/

parsers
```
Stylis x 53.77 ops/sec ±4.36% (58 runs sampled)
Stylis closure compiler x 71.62 ops/sec ±1.50% (64 runs sampled)
```

prefixers
```
Stylis x 47.98 ops/sec ±18.42% (67 runs sampled)
Stylis Closure x 57.76 ops/sec ±23.74% (78 runs sampled)
```

preprocessors
```
Stylis x 37.26 ops/sec ±18.23% (67 runs sampled)
Stylis Closure x 36.72 ops/sec ±15.76% (67 runs sampled)
```

**Comment by leeoniya** [comment]
certainly ymmv. it very likely varies per codebase and per platform. just a heads up.
