### ISSUE TITLE
ie8 error

### ISSUE THREAD

**Issue by alena-ilina** [thysultan/stylis.js#88]
Hello!

I use styled components in my project. And it doesn't work in ie8. I have this error:

IE8 expected ']' in regular expression

At this row:

var propertyptn = /([^]*?);/g /* match properties leading semicolon */

I found this solution at [stackoverflow](https://stackoverflow.com/questions/21931523/ie8-expected-in-regular-expression)

What do you think about it?

**Comment by thysultan** [comment]
LGTM, can you open a pull request for this?

**Comment by alena-ilina** [comment]
I've opened a pull request https://github.com/thysultan/stylis.js/pull/89

**Comment by alena-ilina** [comment]
Thank's a lot!

But did you push changes in npm?

**Comment by thysultan** [comment]
Thanks, 3.4.8 is out with this patch.
