### ISSUE TITLE
Autoprefixing configuration

### ISSUE THREAD

**Issue by gertsonderby** [thysultan/stylis.js#9]
Different browsers require different sets of prefixes - see http://caniuse.com/. There does not currently seem to be any support for configuring which browsers should be supported with prefixing. Is it intended to be a manual setting - flagging every single prefix you need on your own - or to match e.g. [postCSS](https://github.com/postcss/autoprefixer) functionality where you can set which browsers to support?

**Comment by gertsonderby** [comment]
My current use case requires iPhone 5 or better, plus last two active versions of major browsers, and the browsers used in Sweden at over 1% level. I can configure this for postCSS' autoprefixer with a three line config.

**Comment by thysultan** [comment]
@gertsonderby stylis prefixes for IE9+ and old android versions with substantial user share where it can and must but also tries to avoid excessive prefixing where it's not worth it, i.e properties that have wide coverage etc. Is there something i'm missing that should be prefixed?

**Comment by gertsonderby** [comment]
So... no configuration is possible at all?

I had an iPhone 6 fail to show `width: max-content`, had to manually add that one, to take an example of a thing I ran into.

**Comment by thysultan** [comment]
@gertsonderby You can add middleware to configure what happens to the output though styled-components does not expose stylis middleware entry point. Will add `max-content` and `min-content`.

**Comment by thysultan** [comment]
@gertsonderby thanks for the find, patched in v1.2.6.
