### ISSUE TITLE
text-decoration vendor prefixes

### ISSUE THREAD

**Issue by teddybradford** [thysultan/stylis.js#92]
It appears that the extended `text-decoration` properties (`text-decoration-line`, `text-decoration-color`, and `text-decoration-style`) don't get vendor prefixes applied to them. https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration

For example, Safari requires a `-webkit` prefix for `text-decoration: underline wavy #999;` to be rendered.

**Comment by thysultan** [comment]
Do know where i can find a definitive list of which properties `webkit` requires a prefix for? or do you think it would be easier to just add a `-webkit-` prefixed version for all variants regardless.

**Comment by teddybradford** [comment]
@thysultan I don't know if there is an official list somewhere, but from my testing it seems that the `-webkit` prefix is required in Safari for any extended `text-decoration` shorthand beyond `text-decoration: {style}`, and all the extra `text-decoration-{type}` need the prefix as well.

In other words, it probably makes sense to just add the `-webkit` prefix for all variants, including `text-decoration` shorthand.

**Comment by thysultan** [comment]
Patched in 3.4.9. I have a feeling someone is going to open an issue about `text-decoration` having a vendor prefix variant, hopefully this issue might help as good reference for why we do it. Thanks for finding this.
