### ISSUE TITLE
Async plugins

### ISSUE THREAD

**Issue by exogen** [thysultan/stylis.js#98]
Currently plugins must be synchronous – they can return a transformed string.

This unfortunately precludes the use of any middleware that may be asynchronous. It would be nice to be able to return a Promise from a plugin.

For example, currently it's not really possible to include something like `stylelint` (at the `-1` stage), because the `stylelint` Node API is async. The only workaround would be to use synchronous process spawning APIs to run stylelint in a separate process every time `stylis()` is called.

This would be a breaking change since `stylis()` could no longer be synchronous.

**Comment by thysultan** [comment]
Is there something stopping it from being in the -2(post-process) stage. I think it is possible to support promises in stage -1(preparation stage) though i'm hesitant to, unless there are use cases that cannot otherwise work without this. Can you post an example of what you're trying to do?

**Comment by Andarist** [comment]
With the upcoming v4 you will have greater control over plugins - because most likely you will have to assemble parsing pipeline yourself out of the provided bits, so it should become fairly trivial to adjust your pipeline to support async plugins. Stay tuned for this.
